# coding: utf-8

"""
    AgentDrive

    AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentdrive_sdk.models.find_hit_out import FindHitOut

class TestFindHitOut(unittest.TestCase):
    """FindHitOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FindHitOut:
        """Test FindHitOut
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FindHitOut`
        """
        model = FindHitOut()
        if include_optional:
            return FindHitOut(
                art_id = '',
                drive_id = '',
                path = '',
                url = '',
                content_type = '',
                file_type = '',
                labels = [
                    ''
                    ],
                visibility = 'public',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                version_number = 56,
                modality = 'text',
                ord = 56,
                text = '',
                snippet = '',
                score = 1.337,
                rank_lexical = 56,
                rank_semantic = 56,
                char_start = 56,
                char_end = 56,
                page_start = 56,
                page_end = 56,
                time_start_ms = 56,
                time_end_ms = 56
            )
        else:
            return FindHitOut(
                art_id = '',
                drive_id = '',
                path = '',
                url = '',
                content_type = '',
                file_type = '',
                visibility = 'public',
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                version_number = 56,
                modality = 'text',
                ord = 56,
                text = '',
                snippet = '',
                score = 1.337,
        )
        """

    def testFindHitOut(self):
        """Test FindHitOut"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
