# coding: utf-8

"""
    AgentDrive

    AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentdrive_sdk.models.extension_exchange_response import ExtensionExchangeResponse

class TestExtensionExchangeResponse(unittest.TestCase):
    """ExtensionExchangeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExtensionExchangeResponse:
        """Test ExtensionExchangeResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExtensionExchangeResponse`
        """
        model = ExtensionExchangeResponse()
        if include_optional:
            return ExtensionExchangeResponse(
                access_token = '',
                token_type = 'Bearer',
                expires_in = 56,
                scope = 'extension',
                identity_assertion = '',
                drive_id = ''
            )
        else:
            return ExtensionExchangeResponse(
                access_token = '',
                expires_in = 56,
                identity_assertion = '',
                drive_id = '',
        )
        """

    def testExtensionExchangeResponse(self):
        """Test ExtensionExchangeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
