# coding: utf-8

"""
    AgentDrive

    AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentdrive_sdk.api.claim_ui_api import ClaimUiApi


class TestClaimUiApi(unittest.TestCase):
    """ClaimUiApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ClaimUiApi()

    def tearDown(self) -> None:
        pass

    def test_claim_complete_agent_identity_claim_complete_post(self) -> None:
        """Test case for claim_complete_agent_identity_claim_complete_post

        Claim Complete
        """
        pass

    def test_claim_page_claim_get(self) -> None:
        """Test case for claim_page_claim_get

        Claim Page
        """
        pass


if __name__ == '__main__':
    unittest.main()
