# coding: utf-8

"""
    AgentDrive

    AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentdrive_sdk.api.drives_api import DrivesApi


class TestDrivesApi(unittest.TestCase):
    """DrivesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DrivesApi()

    def tearDown(self) -> None:
        pass

    def test_create_drive_route_v0_drives_post(self) -> None:
        """Test case for create_drive_route_v0_drives_post

        Create a drive in your active workspace
        """
        pass

    def test_list_drives_route_v0_drives_get(self) -> None:
        """Test case for list_drives_route_v0_drives_get

        List the drives you can see
        """
        pass

    def test_rename_drive_route_v0_drives_drive_id_patch(self) -> None:
        """Test case for rename_drive_route_v0_drives_drive_id_patch

        Rename a drive you own
        """
        pass

    def test_rotate_drive_key_route_v0_drives_drive_id_keys_rotate_post(self) -> None:
        """Test case for rotate_drive_key_route_v0_drives_drive_id_keys_rotate_post

        Rotate a drive's API key
        """
        pass


if __name__ == '__main__':
    unittest.main()
