# coding: utf-8

"""
    AgentDrive

    AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentdrive_sdk.models.workspace_create_out import WorkspaceCreateOut

class TestWorkspaceCreateOut(unittest.TestCase):
    """WorkspaceCreateOut unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkspaceCreateOut:
        """Test WorkspaceCreateOut
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WorkspaceCreateOut`
        """
        model = WorkspaceCreateOut()
        if include_optional:
            return WorkspaceCreateOut(
                workspace = agentdrive_sdk.models.workspace_out.WorkspaceOut(
                    id = '', 
                    name = '', 
                    role = 'admin', 
                    tier_id = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                starter_drive_id = '',
                starter_drive_api_key = ''
            )
        else:
            return WorkspaceCreateOut(
                workspace = agentdrive_sdk.models.workspace_out.WorkspaceOut(
                    id = '', 
                    name = '', 
                    role = 'admin', 
                    tier_id = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                starter_drive_id = '',
                starter_drive_api_key = '',
        )
        """

    def testWorkspaceCreateOut(self):
        """Test WorkspaceCreateOut"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
