# coding: utf-8

"""
    AgentDrive

    AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from agentdrive_sdk.api.feedback_internal_api import FeedbackInternalApi


class TestFeedbackInternalApi(unittest.TestCase):
    """FeedbackInternalApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FeedbackInternalApi()

    def tearDown(self) -> None:
        pass

    def test_append_event_internal_feedback_fbk_id_events_post(self) -> None:
        """Test case for append_event_internal_feedback_fbk_id_events_post

        Append Event
        """
        pass

    def test_contact_internal_feedback_fbk_id_contact_get(self) -> None:
        """Test case for contact_internal_feedback_fbk_id_contact_get

        Contact
        """
        pass

    def test_get_attachment_internal_feedback_fbk_id_attachments_fba_id_get(self) -> None:
        """Test case for get_attachment_internal_feedback_fbk_id_attachments_fba_id_get

        Get Attachment
        """
        pass

    def test_get_ticket_internal_feedback_fbk_id_get(self) -> None:
        """Test case for get_ticket_internal_feedback_fbk_id_get

        Get Ticket
        """
        pass

    def test_list_attachments_internal_feedback_fbk_id_attachments_get(self) -> None:
        """Test case for list_attachments_internal_feedback_fbk_id_attachments_get

        List Attachments
        """
        pass

    def test_list_feedback_internal_feedback_get(self) -> None:
        """Test case for list_feedback_internal_feedback_get

        List Feedback
        """
        pass

    def test_notified_internal_feedback_fbk_id_notified_post(self) -> None:
        """Test case for notified_internal_feedback_fbk_id_notified_post

        Notified
        """
        pass

    def test_pending_notifications_internal_feedback_pending_notifications_get(self) -> None:
        """Test case for pending_notifications_internal_feedback_pending_notifications_get

        Pending Notifications
        """
        pass

    def test_transition_internal_feedback_fbk_id_transition_post(self) -> None:
        """Test case for transition_internal_feedback_fbk_id_transition_post

        Transition
        """
        pass


if __name__ == '__main__':
    unittest.main()
