/* tslint:disable */
/* eslint-disable */
/**
 * AgentDrive
 * AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';

export interface ClaimCompleteAgentIdentityClaimCompletePostRequest {
    claimAttemptToken: string;
    userCode: string;
    csrf: string;
    decision?: string;
    orgName?: string;
}

export interface ClaimPageClaimGetRequest {
    code?: string | null;
}

/**
 * 
 */
export class ClaimUiApi extends runtime.BaseAPI {

    /**
     * Creates request options for claimCompleteAgentIdentityClaimCompletePost without sending the request
     */
    async claimCompleteAgentIdentityClaimCompletePostRequestOpts(requestParameters: ClaimCompleteAgentIdentityClaimCompletePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['claimAttemptToken'] == null) {
            throw new runtime.RequiredError(
                'claimAttemptToken',
                'Required parameter "claimAttemptToken" was null or undefined when calling claimCompleteAgentIdentityClaimCompletePost().'
            );
        }

        if (requestParameters['userCode'] == null) {
            throw new runtime.RequiredError(
                'userCode',
                'Required parameter "userCode" was null or undefined when calling claimCompleteAgentIdentityClaimCompletePost().'
            );
        }

        if (requestParameters['csrf'] == null) {
            throw new runtime.RequiredError(
                'csrf',
                'Required parameter "csrf" was null or undefined when calling claimCompleteAgentIdentityClaimCompletePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['claimAttemptToken'] != null) {
            formParams.append('claim_attempt_token', requestParameters['claimAttemptToken'] as any);
        }

        if (requestParameters['userCode'] != null) {
            formParams.append('user_code', requestParameters['userCode'] as any);
        }

        if (requestParameters['decision'] != null) {
            formParams.append('decision', requestParameters['decision'] as any);
        }

        if (requestParameters['orgName'] != null) {
            formParams.append('org_name', requestParameters['orgName'] as any);
        }

        if (requestParameters['csrf'] != null) {
            formParams.append('csrf', requestParameters['csrf'] as any);
        }


        let urlPath = `/agent/identity/claim/complete`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Browser-form submit from `/claim`. CSRF-gated + WorkOS-session-gated. Atomically binds the drive to the user OR marks the attempt denied.  See design §5.3 for the algorithm — concurrency note: we `SELECT … FOR UPDATE` on the claim_attempts row to serialize the double-click case before running the drive_limit gate.
     * Claim Complete
     */
    async claimCompleteAgentIdentityClaimCompletePostRaw(requestParameters: ClaimCompleteAgentIdentityClaimCompletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.claimCompleteAgentIdentityClaimCompletePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Browser-form submit from `/claim`. CSRF-gated + WorkOS-session-gated. Atomically binds the drive to the user OR marks the attempt denied.  See design §5.3 for the algorithm — concurrency note: we `SELECT … FOR UPDATE` on the claim_attempts row to serialize the double-click case before running the drive_limit gate.
     * Claim Complete
     */
    async claimCompleteAgentIdentityClaimCompletePost(requestParameters: ClaimCompleteAgentIdentityClaimCompletePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.claimCompleteAgentIdentityClaimCompletePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for claimPageClaimGet without sending the request
     */
    async claimPageClaimGetRequestOpts(requestParameters: ClaimPageClaimGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['code'] != null) {
            queryParameters['code'] = requestParameters['code'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/claim`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Three states, each rendered via the same template with a different `state` discriminator. The user_code is read from the query string so the URL is shareable from the agent\'s UI.  Auth: WorkOS browser session required. If absent, redirect to `/auth/login?return_to=/claim?code=<code>` and the user lands back here after sign-in.
     * Claim Page
     */
    async claimPageClaimGetRaw(requestParameters: ClaimPageClaimGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.claimPageClaimGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Three states, each rendered via the same template with a different `state` discriminator. The user_code is read from the query string so the URL is shareable from the agent\'s UI.  Auth: WorkOS browser session required. If absent, redirect to `/auth/login?return_to=/claim?code=<code>` and the user lands back here after sign-in.
     * Claim Page
     */
    async claimPageClaimGet(requestParameters: ClaimPageClaimGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.claimPageClaimGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
