/* tslint:disable */
/* eslint-disable */
/**
 * AgentDrive
 * AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type DriveCreateIn,
    DriveCreateInFromJSON,
    DriveCreateInToJSON,
} from '../models/DriveCreateIn';
import {
    type DriveCreateOut,
    DriveCreateOutFromJSON,
    DriveCreateOutToJSON,
} from '../models/DriveCreateOut';
import {
    type DriveKeyRotateOut,
    DriveKeyRotateOutFromJSON,
    DriveKeyRotateOutToJSON,
} from '../models/DriveKeyRotateOut';
import {
    type DriveList,
    DriveListFromJSON,
    DriveListToJSON,
} from '../models/DriveList';
import {
    type DriveOut,
    DriveOutFromJSON,
    DriveOutToJSON,
} from '../models/DriveOut';
import {
    type DriveRenameIn,
    DriveRenameInFromJSON,
    DriveRenameInToJSON,
} from '../models/DriveRenameIn';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';

export interface CreateDriveRouteV0DrivesPostRequest {
    driveCreateIn: DriveCreateIn;
    authorization?: string | null;
}

export interface ListDrivesRouteV0DrivesGetRequest {
    authorization?: string | null;
}

export interface RenameDriveRouteV0DrivesDriveIdPatchRequest {
    driveId: string;
    driveRenameIn: DriveRenameIn;
    authorization?: string | null;
}

export interface RotateDriveKeyRouteV0DrivesDriveIdKeysRotatePostRequest {
    driveId: string;
    authorization?: string | null;
}

/**
 * 
 */
export class DrivesApi extends runtime.BaseAPI {

    /**
     * Creates request options for createDriveRouteV0DrivesPost without sending the request
     */
    async createDriveRouteV0DrivesPostRequestOpts(requestParameters: CreateDriveRouteV0DrivesPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['driveCreateIn'] == null) {
            throw new runtime.RequiredError(
                'driveCreateIn',
                'Required parameter "driveCreateIn" was null or undefined when calling createDriveRouteV0DrivesPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/v0/drives`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DriveCreateInToJSON(requestParameters['driveCreateIn']),
        };
    }

    /**
     * Create a named drive. Any **member** of the workspace may create one; the creator becomes its **owner**. Requires a `full`-scope user token. The response carries the drive\'s `ad_live_` API key **once** (`api_key`) — store it now, it is never returned again (rotate via `POST /v0/drives/{id}/keys/rotate`).  The target workspace is the user\'s active organization (`users.default_org`); cross-workspace creation names no other workspace in v0.  A member may own at most a fixed number of drives per workspace (workspaces-design §4.5). A caller at the limit is blocked with `403 DRIVE_LIMIT_REACHED`; this is a hard cap, not a paywall.
     * Create a drive in your active workspace
     */
    async createDriveRouteV0DrivesPostRaw(requestParameters: CreateDriveRouteV0DrivesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DriveCreateOut>> {
        const requestOptions = await this.createDriveRouteV0DrivesPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DriveCreateOutFromJSON(jsonValue));
    }

    /**
     * Create a named drive. Any **member** of the workspace may create one; the creator becomes its **owner**. Requires a `full`-scope user token. The response carries the drive\'s `ad_live_` API key **once** (`api_key`) — store it now, it is never returned again (rotate via `POST /v0/drives/{id}/keys/rotate`).  The target workspace is the user\'s active organization (`users.default_org`); cross-workspace creation names no other workspace in v0.  A member may own at most a fixed number of drives per workspace (workspaces-design §4.5). A caller at the limit is blocked with `403 DRIVE_LIMIT_REACHED`; this is a hard cap, not a paywall.
     * Create a drive in your active workspace
     */
    async createDriveRouteV0DrivesPost(requestParameters: CreateDriveRouteV0DrivesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DriveCreateOut> {
        const response = await this.createDriveRouteV0DrivesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listDrivesRouteV0DrivesGet without sending the request
     */
    async listDrivesRouteV0DrivesGetRequestOpts(requestParameters: ListDrivesRouteV0DrivesGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/v0/drives`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns drive **metadata** (workspaces-design §4.2): an **admin** sees the whole active workspace\'s drive inventory (every owner); a **member** sees only the drives they own. Metadata only — owner, size, timestamps — never a raw API key, and never an authorization to read a drive\'s contents. A `read`-scope token may call this; mutations require `full`.
     * List the drives you can see
     */
    async listDrivesRouteV0DrivesGetRaw(requestParameters: ListDrivesRouteV0DrivesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DriveList>> {
        const requestOptions = await this.listDrivesRouteV0DrivesGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DriveListFromJSON(jsonValue));
    }

    /**
     * Returns drive **metadata** (workspaces-design §4.2): an **admin** sees the whole active workspace\'s drive inventory (every owner); a **member** sees only the drives they own. Metadata only — owner, size, timestamps — never a raw API key, and never an authorization to read a drive\'s contents. A `read`-scope token may call this; mutations require `full`.
     * List the drives you can see
     */
    async listDrivesRouteV0DrivesGet(requestParameters: ListDrivesRouteV0DrivesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DriveList> {
        const response = await this.listDrivesRouteV0DrivesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for renameDriveRouteV0DrivesDriveIdPatch without sending the request
     */
    async renameDriveRouteV0DrivesDriveIdPatchRequestOpts(requestParameters: RenameDriveRouteV0DrivesDriveIdPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['driveId'] == null) {
            throw new runtime.RequiredError(
                'driveId',
                'Required parameter "driveId" was null or undefined when calling renameDriveRouteV0DrivesDriveIdPatch().'
            );
        }

        if (requestParameters['driveRenameIn'] == null) {
            throw new runtime.RequiredError(
                'driveRenameIn',
                'Required parameter "driveRenameIn" was null or undefined when calling renameDriveRouteV0DrivesDriveIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/v0/drives/{drive_id}`;
        urlPath = urlPath.replace('{drive_id}', encodeURIComponent(String(requestParameters['driveId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: DriveRenameInToJSON(requestParameters['driveRenameIn']),
        };
    }

    /**
     * Rename a drive. **Owner only** — a drive id that isn\'t yours returns 404 (no-leak). Requires a `full`-scope user token.
     * Rename a drive you own
     */
    async renameDriveRouteV0DrivesDriveIdPatchRaw(requestParameters: RenameDriveRouteV0DrivesDriveIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DriveOut>> {
        const requestOptions = await this.renameDriveRouteV0DrivesDriveIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DriveOutFromJSON(jsonValue));
    }

    /**
     * Rename a drive. **Owner only** — a drive id that isn\'t yours returns 404 (no-leak). Requires a `full`-scope user token.
     * Rename a drive you own
     */
    async renameDriveRouteV0DrivesDriveIdPatch(requestParameters: RenameDriveRouteV0DrivesDriveIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DriveOut> {
        const response = await this.renameDriveRouteV0DrivesDriveIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for rotateDriveKeyRouteV0DrivesDriveIdKeysRotatePost without sending the request
     */
    async rotateDriveKeyRouteV0DrivesDriveIdKeysRotatePostRequestOpts(requestParameters: RotateDriveKeyRouteV0DrivesDriveIdKeysRotatePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['driveId'] == null) {
            throw new runtime.RequiredError(
                'driveId',
                'Required parameter "driveId" was null or undefined when calling rotateDriveKeyRouteV0DrivesDriveIdKeysRotatePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/v0/drives/{drive_id}/keys/rotate`;
        urlPath = urlPath.replace('{drive_id}', encodeURIComponent(String(requestParameters['driveId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Generate a fresh `ad_live_` key for a drive you own and invalidate the old one immediately. **Owner only** (404 no-leak otherwise) and requires a `full`-scope user token. The new key is returned **once** — store it now.
     * Rotate a drive\'s API key
     */
    async rotateDriveKeyRouteV0DrivesDriveIdKeysRotatePostRaw(requestParameters: RotateDriveKeyRouteV0DrivesDriveIdKeysRotatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DriveKeyRotateOut>> {
        const requestOptions = await this.rotateDriveKeyRouteV0DrivesDriveIdKeysRotatePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DriveKeyRotateOutFromJSON(jsonValue));
    }

    /**
     * Generate a fresh `ad_live_` key for a drive you own and invalidate the old one immediately. **Owner only** (404 no-leak otherwise) and requires a `full`-scope user token. The new key is returned **once** — store it now.
     * Rotate a drive\'s API key
     */
    async rotateDriveKeyRouteV0DrivesDriveIdKeysRotatePost(requestParameters: RotateDriveKeyRouteV0DrivesDriveIdKeysRotatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DriveKeyRotateOut> {
        const response = await this.rotateDriveKeyRouteV0DrivesDriveIdKeysRotatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
