/* tslint:disable */
/* eslint-disable */
/**
 * AgentDrive
 * AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';

export interface AppendEventInternalFeedbackFbkIdEventsPostRequest {
    fbkId: string;
    requestBody: { [key: string]: any; };
}

export interface ContactInternalFeedbackFbkIdContactGetRequest {
    fbkId: string;
}

export interface GetAttachmentInternalFeedbackFbkIdAttachmentsFbaIdGetRequest {
    fbkId: string;
    fbaId: string;
}

export interface GetTicketInternalFeedbackFbkIdGetRequest {
    fbkId: string;
}

export interface ListAttachmentsInternalFeedbackFbkIdAttachmentsGetRequest {
    fbkId: string;
}

export interface ListFeedbackInternalFeedbackGetRequest {
    status?: string;
    limit?: number;
}

export interface NotifiedInternalFeedbackFbkIdNotifiedPostRequest {
    fbkId: string;
    requestBody: { [key: string]: any; };
}

export interface PendingNotificationsInternalFeedbackPendingNotificationsGetRequest {
    limit?: number;
}

export interface TransitionInternalFeedbackFbkIdTransitionPostRequest {
    fbkId: string;
    requestBody: { [key: string]: any; };
}

/**
 * 
 */
export class FeedbackInternalApi extends runtime.BaseAPI {

    /**
     * Creates request options for appendEventInternalFeedbackFbkIdEventsPost without sending the request
     */
    async appendEventInternalFeedbackFbkIdEventsPostRequestOpts(requestParameters: AppendEventInternalFeedbackFbkIdEventsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['fbkId'] == null) {
            throw new runtime.RequiredError(
                'fbkId',
                'Required parameter "fbkId" was null or undefined when calling appendEventInternalFeedbackFbkIdEventsPost().'
            );
        }

        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling appendEventInternalFeedbackFbkIdEventsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/internal/feedback/{fbk_id}/events`;
        urlPath = urlPath.replace('{fbk_id}', encodeURIComponent(String(requestParameters['fbkId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        };
    }

    /**
     * Record a non-transition timeline entry (reply_received, issue_created, pr_opened, unsubscribed, …) as the authenticated lane. email_sent is rejected — use /notified.
     * Append Event
     */
    async appendEventInternalFeedbackFbkIdEventsPostRaw(requestParameters: AppendEventInternalFeedbackFbkIdEventsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.appendEventInternalFeedbackFbkIdEventsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Record a non-transition timeline entry (reply_received, issue_created, pr_opened, unsubscribed, …) as the authenticated lane. email_sent is rejected — use /notified.
     * Append Event
     */
    async appendEventInternalFeedbackFbkIdEventsPost(requestParameters: AppendEventInternalFeedbackFbkIdEventsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.appendEventInternalFeedbackFbkIdEventsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for contactInternalFeedbackFbkIdContactGet without sending the request
     */
    async contactInternalFeedbackFbkIdContactGetRequestOpts(requestParameters: ContactInternalFeedbackFbkIdContactGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['fbkId'] == null) {
            throw new runtime.RequiredError(
                'fbkId',
                'Required parameter "fbkId" was null or undefined when calling contactInternalFeedbackFbkIdContactGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/internal/feedback/{fbk_id}/contact`;
        urlPath = urlPath.replace('{fbk_id}', encodeURIComponent(String(requestParameters['fbkId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * The ONLY place filer identity crosses to a lane. Fails closed (contact=true AND past `received`) and every call — hit or miss — lands an email_lookup audit event (§5.4).
     * Contact
     */
    async contactInternalFeedbackFbkIdContactGetRaw(requestParameters: ContactInternalFeedbackFbkIdContactGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.contactInternalFeedbackFbkIdContactGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * The ONLY place filer identity crosses to a lane. Fails closed (contact=true AND past `received`) and every call — hit or miss — lands an email_lookup audit event (§5.4).
     * Contact
     */
    async contactInternalFeedbackFbkIdContactGet(requestParameters: ContactInternalFeedbackFbkIdContactGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.contactInternalFeedbackFbkIdContactGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAttachmentInternalFeedbackFbkIdAttachmentsFbaIdGet without sending the request
     */
    async getAttachmentInternalFeedbackFbkIdAttachmentsFbaIdGetRequestOpts(requestParameters: GetAttachmentInternalFeedbackFbkIdAttachmentsFbaIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['fbkId'] == null) {
            throw new runtime.RequiredError(
                'fbkId',
                'Required parameter "fbkId" was null or undefined when calling getAttachmentInternalFeedbackFbkIdAttachmentsFbaIdGet().'
            );
        }

        if (requestParameters['fbaId'] == null) {
            throw new runtime.RequiredError(
                'fbaId',
                'Required parameter "fbaId" was null or undefined when calling getAttachmentInternalFeedbackFbkIdAttachmentsFbaIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/internal/feedback/{fbk_id}/attachments/{fba_id}`;
        urlPath = urlPath.replace('{fbk_id}', encodeURIComponent(String(requestParameters['fbkId'])));
        urlPath = urlPath.replace('{fba_id}', encodeURIComponent(String(requestParameters['fbaId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Attachment bytes for description-writing (triage only).
     * Get Attachment
     */
    async getAttachmentInternalFeedbackFbkIdAttachmentsFbaIdGetRaw(requestParameters: GetAttachmentInternalFeedbackFbkIdAttachmentsFbaIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.getAttachmentInternalFeedbackFbkIdAttachmentsFbaIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Attachment bytes for description-writing (triage only).
     * Get Attachment
     */
    async getAttachmentInternalFeedbackFbkIdAttachmentsFbaIdGet(requestParameters: GetAttachmentInternalFeedbackFbkIdAttachmentsFbaIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getAttachmentInternalFeedbackFbkIdAttachmentsFbaIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTicketInternalFeedbackFbkIdGet without sending the request
     */
    async getTicketInternalFeedbackFbkIdGetRequestOpts(requestParameters: GetTicketInternalFeedbackFbkIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['fbkId'] == null) {
            throw new runtime.RequiredError(
                'fbkId',
                'Required parameter "fbkId" was null or undefined when calling getTicketInternalFeedbackFbkIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/internal/feedback/{fbk_id}`;
        urlPath = urlPath.replace('{fbk_id}', encodeURIComponent(String(requestParameters['fbkId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * One ticket + its timeline (triage context, comms routing, the interactive \'show me fbk_x\' read).
     * Get Ticket
     */
    async getTicketInternalFeedbackFbkIdGetRaw(requestParameters: GetTicketInternalFeedbackFbkIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.getTicketInternalFeedbackFbkIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * One ticket + its timeline (triage context, comms routing, the interactive \'show me fbk_x\' read).
     * Get Ticket
     */
    async getTicketInternalFeedbackFbkIdGet(requestParameters: GetTicketInternalFeedbackFbkIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.getTicketInternalFeedbackFbkIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listAttachmentsInternalFeedbackFbkIdAttachmentsGet without sending the request
     */
    async listAttachmentsInternalFeedbackFbkIdAttachmentsGetRequestOpts(requestParameters: ListAttachmentsInternalFeedbackFbkIdAttachmentsGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['fbkId'] == null) {
            throw new runtime.RequiredError(
                'fbkId',
                'Required parameter "fbkId" was null or undefined when calling listAttachmentsInternalFeedbackFbkIdAttachmentsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/internal/feedback/{fbk_id}/attachments`;
        urlPath = urlPath.replace('{fbk_id}', encodeURIComponent(String(requestParameters['fbkId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Attachment metadata — the triage lane describes these into the issue; bytes never reach GitHub (§5.2.1).
     * List Attachments
     */
    async listAttachmentsInternalFeedbackFbkIdAttachmentsGetRaw(requestParameters: ListAttachmentsInternalFeedbackFbkIdAttachmentsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.listAttachmentsInternalFeedbackFbkIdAttachmentsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Attachment metadata — the triage lane describes these into the issue; bytes never reach GitHub (§5.2.1).
     * List Attachments
     */
    async listAttachmentsInternalFeedbackFbkIdAttachmentsGet(requestParameters: ListAttachmentsInternalFeedbackFbkIdAttachmentsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listAttachmentsInternalFeedbackFbkIdAttachmentsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listFeedbackInternalFeedbackGet without sending the request
     */
    async listFeedbackInternalFeedbackGetRequestOpts(requestParameters: ListFeedbackInternalFeedbackGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/internal/feedback`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Work-finding query (oldest first). Triage drains `received`; the sweeps read `triaged`/`in_progress`.
     * List Feedback
     */
    async listFeedbackInternalFeedbackGetRaw(requestParameters: ListFeedbackInternalFeedbackGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.listFeedbackInternalFeedbackGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Work-finding query (oldest first). Triage drains `received`; the sweeps read `triaged`/`in_progress`.
     * List Feedback
     */
    async listFeedbackInternalFeedbackGet(requestParameters: ListFeedbackInternalFeedbackGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.listFeedbackInternalFeedbackGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for notifiedInternalFeedbackFbkIdNotifiedPost without sending the request
     */
    async notifiedInternalFeedbackFbkIdNotifiedPostRequestOpts(requestParameters: NotifiedInternalFeedbackFbkIdNotifiedPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['fbkId'] == null) {
            throw new runtime.RequiredError(
                'fbkId',
                'Required parameter "fbkId" was null or undefined when calling notifiedInternalFeedbackFbkIdNotifiedPost().'
            );
        }

        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling notifiedInternalFeedbackFbkIdNotifiedPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/internal/feedback/{fbk_id}/notified`;
        urlPath = urlPath.replace('{fbk_id}', encodeURIComponent(String(requestParameters['fbkId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        };
    }

    /**
     * Notification-ledger write. `stage` is required — it IS the idempotency key (§5.1 unique index). Returns recorded=false when this (feedback, stage) was already sent.
     * Notified
     */
    async notifiedInternalFeedbackFbkIdNotifiedPostRaw(requestParameters: NotifiedInternalFeedbackFbkIdNotifiedPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.notifiedInternalFeedbackFbkIdNotifiedPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Notification-ledger write. `stage` is required — it IS the idempotency key (§5.1 unique index). Returns recorded=false when this (feedback, stage) was already sent.
     * Notified
     */
    async notifiedInternalFeedbackFbkIdNotifiedPost(requestParameters: NotifiedInternalFeedbackFbkIdNotifiedPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.notifiedInternalFeedbackFbkIdNotifiedPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for pendingNotificationsInternalFeedbackPendingNotificationsGet without sending the request
     */
    async pendingNotificationsInternalFeedbackPendingNotificationsGetRequestOpts(requestParameters: PendingNotificationsInternalFeedbackPendingNotificationsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/internal/feedback/pending-notifications`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * The comms lane\'s outbound work: rows past an enabled policy stage, contact=true, no matching email_sent ledger entry — including the §5.3.1 dup fan-out.
     * Pending Notifications
     */
    async pendingNotificationsInternalFeedbackPendingNotificationsGetRaw(requestParameters: PendingNotificationsInternalFeedbackPendingNotificationsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.pendingNotificationsInternalFeedbackPendingNotificationsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * The comms lane\'s outbound work: rows past an enabled policy stage, contact=true, no matching email_sent ledger entry — including the §5.3.1 dup fan-out.
     * Pending Notifications
     */
    async pendingNotificationsInternalFeedbackPendingNotificationsGet(requestParameters: PendingNotificationsInternalFeedbackPendingNotificationsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.pendingNotificationsInternalFeedbackPendingNotificationsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for transitionInternalFeedbackFbkIdTransitionPost without sending the request
     */
    async transitionInternalFeedbackFbkIdTransitionPostRequestOpts(requestParameters: TransitionInternalFeedbackFbkIdTransitionPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['fbkId'] == null) {
            throw new runtime.RequiredError(
                'fbkId',
                'Required parameter "fbkId" was null or undefined when calling transitionInternalFeedbackFbkIdTransitionPost().'
            );
        }

        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling transitionInternalFeedbackFbkIdTransitionPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/internal/feedback/{fbk_id}/transition`;
        urlPath = urlPath.replace('{fbk_id}', encodeURIComponent(String(requestParameters['fbkId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        };
    }

    /**
     * Drive one state-machine edge as the authenticated lane.  409 carries `current_status`; `to` == current is a 200 no-op with `changed: false` (idempotent retries).
     * Transition
     */
    async transitionInternalFeedbackFbkIdTransitionPostRaw(requestParameters: TransitionInternalFeedbackFbkIdTransitionPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.transitionInternalFeedbackFbkIdTransitionPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Drive one state-machine edge as the authenticated lane.  409 carries `current_status`; `to` == current is a 200 no-op with `changed: false` (idempotent retries).
     * Transition
     */
    async transitionInternalFeedbackFbkIdTransitionPost(requestParameters: TransitionInternalFeedbackFbkIdTransitionPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.transitionInternalFeedbackFbkIdTransitionPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
