/* tslint:disable */
/* eslint-disable */
/**
 * AgentDrive
 * AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type HTTPValidationError,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/HTTPValidationError';

export interface AuthorizeDecisionOauth2AuthorizePostRequest {
    csrf: string;
}

/**
 * 
 */
export class McpOauthUiApi extends runtime.BaseAPI {

    /**
     * Creates request options for authorizeDecisionOauth2AuthorizePost without sending the request
     */
    async authorizeDecisionOauth2AuthorizePostRequestOpts(requestParameters: AuthorizeDecisionOauth2AuthorizePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['csrf'] == null) {
            throw new runtime.RequiredError(
                'csrf',
                'Required parameter "csrf" was null or undefined when calling authorizeDecisionOauth2AuthorizePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['csrf'] != null) {
            formParams.append('csrf', requestParameters['csrf'] as any);
        }


        let urlPath = `/oauth2/authorize`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Authorize Decision
     */
    async authorizeDecisionOauth2AuthorizePostRaw(requestParameters: AuthorizeDecisionOauth2AuthorizePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.authorizeDecisionOauth2AuthorizePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Authorize Decision
     */
    async authorizeDecisionOauth2AuthorizePost(requestParameters: AuthorizeDecisionOauth2AuthorizePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.authorizeDecisionOauth2AuthorizePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for authorizePageOauth2AuthorizeGet without sending the request
     */
    async authorizePageOauth2AuthorizeGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/oauth2/authorize`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Authorize Page
     */
    async authorizePageOauth2AuthorizeGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.authorizePageOauth2AuthorizeGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Authorize Page
     */
    async authorizePageOauth2AuthorizeGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.authorizePageOauth2AuthorizeGetRaw(initOverrides);
        return await response.value();
    }

}
