# coding: utf-8

"""
    AgentDrive

    AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DownloadUrlOut(BaseModel):
    """
    A URL the caller can GET to fetch the artifact's bytes.  `direct=True` ⇒ a short-lived signed GCS URL on `storage.googleapis.com` (client downloads straight from GCS; `expires_at` is set). `direct=False` ⇒ the proxy `/download` endpoint on the API host (no expiry) — returned for sub-threshold artifacts or when signing is unavailable. The URL is opaque: callers should not parse it. See large-download-design.md §5.1.
    """ # noqa: E501
    download_url: StrictStr
    direct: StrictBool
    expires_at: Optional[datetime] = None
    size_bytes: StrictInt
    content_type: StrictStr
    filename: StrictStr
    __properties: ClassVar[List[str]] = ["download_url", "direct", "expires_at", "size_bytes", "content_type", "filename"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DownloadUrlOut from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if expires_at (nullable) is None
        # and model_fields_set contains the field
        if self.expires_at is None and "expires_at" in self.model_fields_set:
            _dict['expires_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DownloadUrlOut from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "download_url": obj.get("download_url"),
            "direct": obj.get("direct"),
            "expires_at": obj.get("expires_at"),
            "size_bytes": obj.get("size_bytes"),
            "content_type": obj.get("content_type"),
            "filename": obj.get("filename")
        })
        return _obj


