# coding: utf-8

"""
    AgentDrive

    AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class FindHitOut(BaseModel):
    """
    One passage-level hit from `/v0/find` (hybrid chunk RAG over `embed_chunks`). The unit is a passage, not a file — consecutive `ord` values from the same `art_id` are normal because chunks overlap by ~400 tokens. Span fields are modality-aware: only the pair matching `modality` is populated, the others stay None.
    """ # noqa: E501
    art_id: StrictStr
    drive_id: StrictStr
    path: StrictStr
    url: StrictStr
    content_type: StrictStr
    file_type: StrictStr
    labels: Optional[List[StrictStr]] = None
    visibility: StrictStr
    updated_at: datetime
    version_number: StrictInt
    modality: StrictStr
    ord: StrictInt
    text: StrictStr
    snippet: StrictStr
    score: Union[StrictFloat, StrictInt]
    rank_lexical: Optional[StrictInt] = None
    rank_semantic: Optional[StrictInt] = None
    char_start: Optional[StrictInt] = None
    char_end: Optional[StrictInt] = None
    page_start: Optional[StrictInt] = None
    page_end: Optional[StrictInt] = None
    time_start_ms: Optional[StrictInt] = None
    time_end_ms: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["art_id", "drive_id", "path", "url", "content_type", "file_type", "labels", "visibility", "updated_at", "version_number", "modality", "ord", "text", "snippet", "score", "rank_lexical", "rank_semantic", "char_start", "char_end", "page_start", "page_end", "time_start_ms", "time_end_ms"]

    @field_validator('visibility')
    def visibility_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['public', 'private']):
            raise ValueError("must be one of enum values ('public', 'private')")
        return value

    @field_validator('modality')
    def modality_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['text', 'code', 'pdf', 'image', 'audio', 'video']):
            raise ValueError("must be one of enum values ('text', 'code', 'pdf', 'image', 'audio', 'video')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FindHitOut from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if rank_lexical (nullable) is None
        # and model_fields_set contains the field
        if self.rank_lexical is None and "rank_lexical" in self.model_fields_set:
            _dict['rank_lexical'] = None

        # set to None if rank_semantic (nullable) is None
        # and model_fields_set contains the field
        if self.rank_semantic is None and "rank_semantic" in self.model_fields_set:
            _dict['rank_semantic'] = None

        # set to None if char_start (nullable) is None
        # and model_fields_set contains the field
        if self.char_start is None and "char_start" in self.model_fields_set:
            _dict['char_start'] = None

        # set to None if char_end (nullable) is None
        # and model_fields_set contains the field
        if self.char_end is None and "char_end" in self.model_fields_set:
            _dict['char_end'] = None

        # set to None if page_start (nullable) is None
        # and model_fields_set contains the field
        if self.page_start is None and "page_start" in self.model_fields_set:
            _dict['page_start'] = None

        # set to None if page_end (nullable) is None
        # and model_fields_set contains the field
        if self.page_end is None and "page_end" in self.model_fields_set:
            _dict['page_end'] = None

        # set to None if time_start_ms (nullable) is None
        # and model_fields_set contains the field
        if self.time_start_ms is None and "time_start_ms" in self.model_fields_set:
            _dict['time_start_ms'] = None

        # set to None if time_end_ms (nullable) is None
        # and model_fields_set contains the field
        if self.time_end_ms is None and "time_end_ms" in self.model_fields_set:
            _dict['time_end_ms'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FindHitOut from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "art_id": obj.get("art_id"),
            "drive_id": obj.get("drive_id"),
            "path": obj.get("path"),
            "url": obj.get("url"),
            "content_type": obj.get("content_type"),
            "file_type": obj.get("file_type"),
            "labels": obj.get("labels"),
            "visibility": obj.get("visibility"),
            "updated_at": obj.get("updated_at"),
            "version_number": obj.get("version_number"),
            "modality": obj.get("modality"),
            "ord": obj.get("ord"),
            "text": obj.get("text"),
            "snippet": obj.get("snippet"),
            "score": obj.get("score"),
            "rank_lexical": obj.get("rank_lexical"),
            "rank_semantic": obj.get("rank_semantic"),
            "char_start": obj.get("char_start"),
            "char_end": obj.get("char_end"),
            "page_start": obj.get("page_start"),
            "page_end": obj.get("page_end"),
            "time_start_ms": obj.get("time_start_ms"),
            "time_end_ms": obj.get("time_end_ms")
        })
        return _obj


