/*
AgentDrive

AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agentdrive

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


// FeedbackInternalAPIService FeedbackInternalAPI service
type FeedbackInternalAPIService service

type ApiAppendEventInternalFeedbackFbkIdEventsPostRequest struct {
	ctx context.Context
	ApiService *FeedbackInternalAPIService
	fbkId string
	requestBody *map[string]interface{}
}

func (r ApiAppendEventInternalFeedbackFbkIdEventsPostRequest) RequestBody(requestBody map[string]interface{}) ApiAppendEventInternalFeedbackFbkIdEventsPostRequest {
	r.requestBody = &requestBody
	return r
}

func (r ApiAppendEventInternalFeedbackFbkIdEventsPostRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.AppendEventInternalFeedbackFbkIdEventsPostExecute(r)
}

/*
AppendEventInternalFeedbackFbkIdEventsPost Append Event

Record a non-transition timeline entry (reply_received,
issue_created, pr_opened, unsubscribed, …) as the authenticated
lane. email_sent is rejected — use /notified.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param fbkId
 @return ApiAppendEventInternalFeedbackFbkIdEventsPostRequest
*/
func (a *FeedbackInternalAPIService) AppendEventInternalFeedbackFbkIdEventsPost(ctx context.Context, fbkId string) ApiAppendEventInternalFeedbackFbkIdEventsPostRequest {
	return ApiAppendEventInternalFeedbackFbkIdEventsPostRequest{
		ApiService: a,
		ctx: ctx,
		fbkId: fbkId,
	}
}

// Execute executes the request
//  @return interface{}
func (a *FeedbackInternalAPIService) AppendEventInternalFeedbackFbkIdEventsPostExecute(r ApiAppendEventInternalFeedbackFbkIdEventsPostRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "FeedbackInternalAPIService.AppendEventInternalFeedbackFbkIdEventsPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/internal/feedback/{fbk_id}/events"
	localVarPath = strings.Replace(localVarPath, "{"+"fbk_id"+"}", url.PathEscape(parameterValueToString(r.fbkId, "fbkId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.requestBody == nil {
		return localVarReturnValue, nil, reportError("requestBody is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.requestBody
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiContactInternalFeedbackFbkIdContactGetRequest struct {
	ctx context.Context
	ApiService *FeedbackInternalAPIService
	fbkId string
}

func (r ApiContactInternalFeedbackFbkIdContactGetRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.ContactInternalFeedbackFbkIdContactGetExecute(r)
}

/*
ContactInternalFeedbackFbkIdContactGet Contact

The ONLY place filer identity crosses to a lane. Fails closed
(contact=true AND past `received`) and every call — hit or miss —
lands an email_lookup audit event (§5.4).

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param fbkId
 @return ApiContactInternalFeedbackFbkIdContactGetRequest
*/
func (a *FeedbackInternalAPIService) ContactInternalFeedbackFbkIdContactGet(ctx context.Context, fbkId string) ApiContactInternalFeedbackFbkIdContactGetRequest {
	return ApiContactInternalFeedbackFbkIdContactGetRequest{
		ApiService: a,
		ctx: ctx,
		fbkId: fbkId,
	}
}

// Execute executes the request
//  @return interface{}
func (a *FeedbackInternalAPIService) ContactInternalFeedbackFbkIdContactGetExecute(r ApiContactInternalFeedbackFbkIdContactGetRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "FeedbackInternalAPIService.ContactInternalFeedbackFbkIdContactGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/internal/feedback/{fbk_id}/contact"
	localVarPath = strings.Replace(localVarPath, "{"+"fbk_id"+"}", url.PathEscape(parameterValueToString(r.fbkId, "fbkId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetAttachmentInternalFeedbackFbkIdAttachmentsFbaIdGetRequest struct {
	ctx context.Context
	ApiService *FeedbackInternalAPIService
	fbkId string
	fbaId string
}

func (r ApiGetAttachmentInternalFeedbackFbkIdAttachmentsFbaIdGetRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.GetAttachmentInternalFeedbackFbkIdAttachmentsFbaIdGetExecute(r)
}

/*
GetAttachmentInternalFeedbackFbkIdAttachmentsFbaIdGet Get Attachment

Attachment bytes for description-writing (triage only).

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param fbkId
 @param fbaId
 @return ApiGetAttachmentInternalFeedbackFbkIdAttachmentsFbaIdGetRequest
*/
func (a *FeedbackInternalAPIService) GetAttachmentInternalFeedbackFbkIdAttachmentsFbaIdGet(ctx context.Context, fbkId string, fbaId string) ApiGetAttachmentInternalFeedbackFbkIdAttachmentsFbaIdGetRequest {
	return ApiGetAttachmentInternalFeedbackFbkIdAttachmentsFbaIdGetRequest{
		ApiService: a,
		ctx: ctx,
		fbkId: fbkId,
		fbaId: fbaId,
	}
}

// Execute executes the request
//  @return interface{}
func (a *FeedbackInternalAPIService) GetAttachmentInternalFeedbackFbkIdAttachmentsFbaIdGetExecute(r ApiGetAttachmentInternalFeedbackFbkIdAttachmentsFbaIdGetRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "FeedbackInternalAPIService.GetAttachmentInternalFeedbackFbkIdAttachmentsFbaIdGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/internal/feedback/{fbk_id}/attachments/{fba_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"fbk_id"+"}", url.PathEscape(parameterValueToString(r.fbkId, "fbkId")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"fba_id"+"}", url.PathEscape(parameterValueToString(r.fbaId, "fbaId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetTicketInternalFeedbackFbkIdGetRequest struct {
	ctx context.Context
	ApiService *FeedbackInternalAPIService
	fbkId string
}

func (r ApiGetTicketInternalFeedbackFbkIdGetRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.GetTicketInternalFeedbackFbkIdGetExecute(r)
}

/*
GetTicketInternalFeedbackFbkIdGet Get Ticket

One ticket + its timeline (triage context, comms routing, the
interactive 'show me fbk_x' read).

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param fbkId
 @return ApiGetTicketInternalFeedbackFbkIdGetRequest
*/
func (a *FeedbackInternalAPIService) GetTicketInternalFeedbackFbkIdGet(ctx context.Context, fbkId string) ApiGetTicketInternalFeedbackFbkIdGetRequest {
	return ApiGetTicketInternalFeedbackFbkIdGetRequest{
		ApiService: a,
		ctx: ctx,
		fbkId: fbkId,
	}
}

// Execute executes the request
//  @return interface{}
func (a *FeedbackInternalAPIService) GetTicketInternalFeedbackFbkIdGetExecute(r ApiGetTicketInternalFeedbackFbkIdGetRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "FeedbackInternalAPIService.GetTicketInternalFeedbackFbkIdGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/internal/feedback/{fbk_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"fbk_id"+"}", url.PathEscape(parameterValueToString(r.fbkId, "fbkId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiListAttachmentsInternalFeedbackFbkIdAttachmentsGetRequest struct {
	ctx context.Context
	ApiService *FeedbackInternalAPIService
	fbkId string
}

func (r ApiListAttachmentsInternalFeedbackFbkIdAttachmentsGetRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.ListAttachmentsInternalFeedbackFbkIdAttachmentsGetExecute(r)
}

/*
ListAttachmentsInternalFeedbackFbkIdAttachmentsGet List Attachments

Attachment metadata — the triage lane describes these into the
issue; bytes never reach GitHub (§5.2.1).

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param fbkId
 @return ApiListAttachmentsInternalFeedbackFbkIdAttachmentsGetRequest
*/
func (a *FeedbackInternalAPIService) ListAttachmentsInternalFeedbackFbkIdAttachmentsGet(ctx context.Context, fbkId string) ApiListAttachmentsInternalFeedbackFbkIdAttachmentsGetRequest {
	return ApiListAttachmentsInternalFeedbackFbkIdAttachmentsGetRequest{
		ApiService: a,
		ctx: ctx,
		fbkId: fbkId,
	}
}

// Execute executes the request
//  @return interface{}
func (a *FeedbackInternalAPIService) ListAttachmentsInternalFeedbackFbkIdAttachmentsGetExecute(r ApiListAttachmentsInternalFeedbackFbkIdAttachmentsGetRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "FeedbackInternalAPIService.ListAttachmentsInternalFeedbackFbkIdAttachmentsGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/internal/feedback/{fbk_id}/attachments"
	localVarPath = strings.Replace(localVarPath, "{"+"fbk_id"+"}", url.PathEscape(parameterValueToString(r.fbkId, "fbkId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiListFeedbackInternalFeedbackGetRequest struct {
	ctx context.Context
	ApiService *FeedbackInternalAPIService
	status *string
	limit *int32
}

func (r ApiListFeedbackInternalFeedbackGetRequest) Status(status string) ApiListFeedbackInternalFeedbackGetRequest {
	r.status = &status
	return r
}

func (r ApiListFeedbackInternalFeedbackGetRequest) Limit(limit int32) ApiListFeedbackInternalFeedbackGetRequest {
	r.limit = &limit
	return r
}

func (r ApiListFeedbackInternalFeedbackGetRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.ListFeedbackInternalFeedbackGetExecute(r)
}

/*
ListFeedbackInternalFeedbackGet List Feedback

Work-finding query (oldest first). Triage drains `received`;
the sweeps read `triaged`/`in_progress`.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiListFeedbackInternalFeedbackGetRequest
*/
func (a *FeedbackInternalAPIService) ListFeedbackInternalFeedbackGet(ctx context.Context) ApiListFeedbackInternalFeedbackGetRequest {
	return ApiListFeedbackInternalFeedbackGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return interface{}
func (a *FeedbackInternalAPIService) ListFeedbackInternalFeedbackGetExecute(r ApiListFeedbackInternalFeedbackGetRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "FeedbackInternalAPIService.ListFeedbackInternalFeedbackGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/internal/feedback"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.status != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "status", r.status, "form", "")
	} else {
		var defaultValue string = "received"
		parameterAddToHeaderOrQuery(localVarQueryParams, "status", defaultValue, "form", "")
		r.status = &defaultValue
	}
	if r.limit != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", r.limit, "form", "")
	} else {
		var defaultValue int32 = 20
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", defaultValue, "form", "")
		r.limit = &defaultValue
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiNotifiedInternalFeedbackFbkIdNotifiedPostRequest struct {
	ctx context.Context
	ApiService *FeedbackInternalAPIService
	fbkId string
	requestBody *map[string]interface{}
}

func (r ApiNotifiedInternalFeedbackFbkIdNotifiedPostRequest) RequestBody(requestBody map[string]interface{}) ApiNotifiedInternalFeedbackFbkIdNotifiedPostRequest {
	r.requestBody = &requestBody
	return r
}

func (r ApiNotifiedInternalFeedbackFbkIdNotifiedPostRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.NotifiedInternalFeedbackFbkIdNotifiedPostExecute(r)
}

/*
NotifiedInternalFeedbackFbkIdNotifiedPost Notified

Notification-ledger write. `stage` is required — it IS the
idempotency key (§5.1 unique index). Returns recorded=false when
this (feedback, stage) was already sent.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param fbkId
 @return ApiNotifiedInternalFeedbackFbkIdNotifiedPostRequest
*/
func (a *FeedbackInternalAPIService) NotifiedInternalFeedbackFbkIdNotifiedPost(ctx context.Context, fbkId string) ApiNotifiedInternalFeedbackFbkIdNotifiedPostRequest {
	return ApiNotifiedInternalFeedbackFbkIdNotifiedPostRequest{
		ApiService: a,
		ctx: ctx,
		fbkId: fbkId,
	}
}

// Execute executes the request
//  @return interface{}
func (a *FeedbackInternalAPIService) NotifiedInternalFeedbackFbkIdNotifiedPostExecute(r ApiNotifiedInternalFeedbackFbkIdNotifiedPostRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "FeedbackInternalAPIService.NotifiedInternalFeedbackFbkIdNotifiedPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/internal/feedback/{fbk_id}/notified"
	localVarPath = strings.Replace(localVarPath, "{"+"fbk_id"+"}", url.PathEscape(parameterValueToString(r.fbkId, "fbkId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.requestBody == nil {
		return localVarReturnValue, nil, reportError("requestBody is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.requestBody
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiPendingNotificationsInternalFeedbackPendingNotificationsGetRequest struct {
	ctx context.Context
	ApiService *FeedbackInternalAPIService
	limit *int32
}

func (r ApiPendingNotificationsInternalFeedbackPendingNotificationsGetRequest) Limit(limit int32) ApiPendingNotificationsInternalFeedbackPendingNotificationsGetRequest {
	r.limit = &limit
	return r
}

func (r ApiPendingNotificationsInternalFeedbackPendingNotificationsGetRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.PendingNotificationsInternalFeedbackPendingNotificationsGetExecute(r)
}

/*
PendingNotificationsInternalFeedbackPendingNotificationsGet Pending Notifications

The comms lane's outbound work: rows past an enabled policy
stage, contact=true, no matching email_sent ledger entry —
including the §5.3.1 dup fan-out.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiPendingNotificationsInternalFeedbackPendingNotificationsGetRequest
*/
func (a *FeedbackInternalAPIService) PendingNotificationsInternalFeedbackPendingNotificationsGet(ctx context.Context) ApiPendingNotificationsInternalFeedbackPendingNotificationsGetRequest {
	return ApiPendingNotificationsInternalFeedbackPendingNotificationsGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return interface{}
func (a *FeedbackInternalAPIService) PendingNotificationsInternalFeedbackPendingNotificationsGetExecute(r ApiPendingNotificationsInternalFeedbackPendingNotificationsGetRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "FeedbackInternalAPIService.PendingNotificationsInternalFeedbackPendingNotificationsGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/internal/feedback/pending-notifications"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.limit != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", r.limit, "form", "")
	} else {
		var defaultValue int32 = 50
		parameterAddToHeaderOrQuery(localVarQueryParams, "limit", defaultValue, "form", "")
		r.limit = &defaultValue
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiTransitionInternalFeedbackFbkIdTransitionPostRequest struct {
	ctx context.Context
	ApiService *FeedbackInternalAPIService
	fbkId string
	requestBody *map[string]interface{}
}

func (r ApiTransitionInternalFeedbackFbkIdTransitionPostRequest) RequestBody(requestBody map[string]interface{}) ApiTransitionInternalFeedbackFbkIdTransitionPostRequest {
	r.requestBody = &requestBody
	return r
}

func (r ApiTransitionInternalFeedbackFbkIdTransitionPostRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.TransitionInternalFeedbackFbkIdTransitionPostExecute(r)
}

/*
TransitionInternalFeedbackFbkIdTransitionPost Transition

Drive one state-machine edge as the authenticated lane.

409 carries `current_status`; `to` == current is a 200 no-op with
`changed: false` (idempotent retries).

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param fbkId
 @return ApiTransitionInternalFeedbackFbkIdTransitionPostRequest
*/
func (a *FeedbackInternalAPIService) TransitionInternalFeedbackFbkIdTransitionPost(ctx context.Context, fbkId string) ApiTransitionInternalFeedbackFbkIdTransitionPostRequest {
	return ApiTransitionInternalFeedbackFbkIdTransitionPostRequest{
		ApiService: a,
		ctx: ctx,
		fbkId: fbkId,
	}
}

// Execute executes the request
//  @return interface{}
func (a *FeedbackInternalAPIService) TransitionInternalFeedbackFbkIdTransitionPostExecute(r ApiTransitionInternalFeedbackFbkIdTransitionPostRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "FeedbackInternalAPIService.TransitionInternalFeedbackFbkIdTransitionPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/internal/feedback/{fbk_id}/transition"
	localVarPath = strings.Replace(localVarPath, "{"+"fbk_id"+"}", url.PathEscape(parameterValueToString(r.fbkId, "fbkId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.requestBody == nil {
		return localVarReturnValue, nil, reportError("requestBody is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.requestBody
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
