/*
AgentDrive

AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agentdrive

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the GrantOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GrantOut{}

// GrantOut A live grant. Audit fields (`granted_by_*`, `on_behalf_of`) are surfaced so a manager can see who shared what.
type GrantOut struct {
	Id string `json:"id"`
	ResourceType string `json:"resource_type"`
	ResourceId string `json:"resource_id"`
	PrincipalType string `json:"principal_type"`
	PrincipalId NullableString `json:"principal_id,omitempty"`
	PrincipalEmail NullableString `json:"principal_email,omitempty"`
	Role string `json:"role"`
	GrantedByType string `json:"granted_by_type"`
	GrantedById string `json:"granted_by_id"`
	OnBehalfOf NullableString `json:"on_behalf_of,omitempty"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt NullableTime `json:"expires_at,omitempty"`
	ArtifactsAffected NullableInt32 `json:"artifacts_affected,omitempty"`
}

type _GrantOut GrantOut

// NewGrantOut instantiates a new GrantOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGrantOut(id string, resourceType string, resourceId string, principalType string, role string, grantedByType string, grantedById string, createdAt time.Time) *GrantOut {
	this := GrantOut{}
	this.Id = id
	this.ResourceType = resourceType
	this.ResourceId = resourceId
	this.PrincipalType = principalType
	this.Role = role
	this.GrantedByType = grantedByType
	this.GrantedById = grantedById
	this.CreatedAt = createdAt
	return &this
}

// NewGrantOutWithDefaults instantiates a new GrantOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGrantOutWithDefaults() *GrantOut {
	this := GrantOut{}
	return &this
}

// GetId returns the Id field value
func (o *GrantOut) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GrantOut) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GrantOut) SetId(v string) {
	o.Id = v
}

// GetResourceType returns the ResourceType field value
func (o *GrantOut) GetResourceType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceType
}

// GetResourceTypeOk returns a tuple with the ResourceType field value
// and a boolean to check if the value has been set.
func (o *GrantOut) GetResourceTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceType, true
}

// SetResourceType sets field value
func (o *GrantOut) SetResourceType(v string) {
	o.ResourceType = v
}

// GetResourceId returns the ResourceId field value
func (o *GrantOut) GetResourceId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ResourceId
}

// GetResourceIdOk returns a tuple with the ResourceId field value
// and a boolean to check if the value has been set.
func (o *GrantOut) GetResourceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResourceId, true
}

// SetResourceId sets field value
func (o *GrantOut) SetResourceId(v string) {
	o.ResourceId = v
}

// GetPrincipalType returns the PrincipalType field value
func (o *GrantOut) GetPrincipalType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PrincipalType
}

// GetPrincipalTypeOk returns a tuple with the PrincipalType field value
// and a boolean to check if the value has been set.
func (o *GrantOut) GetPrincipalTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrincipalType, true
}

// SetPrincipalType sets field value
func (o *GrantOut) SetPrincipalType(v string) {
	o.PrincipalType = v
}

// GetPrincipalId returns the PrincipalId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GrantOut) GetPrincipalId() string {
	if o == nil || IsNil(o.PrincipalId.Get()) {
		var ret string
		return ret
	}
	return *o.PrincipalId.Get()
}

// GetPrincipalIdOk returns a tuple with the PrincipalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GrantOut) GetPrincipalIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PrincipalId.Get(), o.PrincipalId.IsSet()
}

// HasPrincipalId returns a boolean if a field has been set.
func (o *GrantOut) HasPrincipalId() bool {
	if o != nil && o.PrincipalId.IsSet() {
		return true
	}

	return false
}

// SetPrincipalId gets a reference to the given NullableString and assigns it to the PrincipalId field.
func (o *GrantOut) SetPrincipalId(v string) {
	o.PrincipalId.Set(&v)
}
// SetPrincipalIdNil sets the value for PrincipalId to be an explicit nil
func (o *GrantOut) SetPrincipalIdNil() {
	o.PrincipalId.Set(nil)
}

// UnsetPrincipalId ensures that no value is present for PrincipalId, not even an explicit nil
func (o *GrantOut) UnsetPrincipalId() {
	o.PrincipalId.Unset()
}

// GetPrincipalEmail returns the PrincipalEmail field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GrantOut) GetPrincipalEmail() string {
	if o == nil || IsNil(o.PrincipalEmail.Get()) {
		var ret string
		return ret
	}
	return *o.PrincipalEmail.Get()
}

// GetPrincipalEmailOk returns a tuple with the PrincipalEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GrantOut) GetPrincipalEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PrincipalEmail.Get(), o.PrincipalEmail.IsSet()
}

// HasPrincipalEmail returns a boolean if a field has been set.
func (o *GrantOut) HasPrincipalEmail() bool {
	if o != nil && o.PrincipalEmail.IsSet() {
		return true
	}

	return false
}

// SetPrincipalEmail gets a reference to the given NullableString and assigns it to the PrincipalEmail field.
func (o *GrantOut) SetPrincipalEmail(v string) {
	o.PrincipalEmail.Set(&v)
}
// SetPrincipalEmailNil sets the value for PrincipalEmail to be an explicit nil
func (o *GrantOut) SetPrincipalEmailNil() {
	o.PrincipalEmail.Set(nil)
}

// UnsetPrincipalEmail ensures that no value is present for PrincipalEmail, not even an explicit nil
func (o *GrantOut) UnsetPrincipalEmail() {
	o.PrincipalEmail.Unset()
}

// GetRole returns the Role field value
func (o *GrantOut) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *GrantOut) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *GrantOut) SetRole(v string) {
	o.Role = v
}

// GetGrantedByType returns the GrantedByType field value
func (o *GrantOut) GetGrantedByType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GrantedByType
}

// GetGrantedByTypeOk returns a tuple with the GrantedByType field value
// and a boolean to check if the value has been set.
func (o *GrantOut) GetGrantedByTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GrantedByType, true
}

// SetGrantedByType sets field value
func (o *GrantOut) SetGrantedByType(v string) {
	o.GrantedByType = v
}

// GetGrantedById returns the GrantedById field value
func (o *GrantOut) GetGrantedById() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.GrantedById
}

// GetGrantedByIdOk returns a tuple with the GrantedById field value
// and a boolean to check if the value has been set.
func (o *GrantOut) GetGrantedByIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GrantedById, true
}

// SetGrantedById sets field value
func (o *GrantOut) SetGrantedById(v string) {
	o.GrantedById = v
}

// GetOnBehalfOf returns the OnBehalfOf field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GrantOut) GetOnBehalfOf() string {
	if o == nil || IsNil(o.OnBehalfOf.Get()) {
		var ret string
		return ret
	}
	return *o.OnBehalfOf.Get()
}

// GetOnBehalfOfOk returns a tuple with the OnBehalfOf field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GrantOut) GetOnBehalfOfOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OnBehalfOf.Get(), o.OnBehalfOf.IsSet()
}

// HasOnBehalfOf returns a boolean if a field has been set.
func (o *GrantOut) HasOnBehalfOf() bool {
	if o != nil && o.OnBehalfOf.IsSet() {
		return true
	}

	return false
}

// SetOnBehalfOf gets a reference to the given NullableString and assigns it to the OnBehalfOf field.
func (o *GrantOut) SetOnBehalfOf(v string) {
	o.OnBehalfOf.Set(&v)
}
// SetOnBehalfOfNil sets the value for OnBehalfOf to be an explicit nil
func (o *GrantOut) SetOnBehalfOfNil() {
	o.OnBehalfOf.Set(nil)
}

// UnsetOnBehalfOf ensures that no value is present for OnBehalfOf, not even an explicit nil
func (o *GrantOut) UnsetOnBehalfOf() {
	o.OnBehalfOf.Unset()
}

// GetCreatedAt returns the CreatedAt field value
func (o *GrantOut) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *GrantOut) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *GrantOut) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GrantOut) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt.Get()
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GrantOut) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpiresAt.Get(), o.ExpiresAt.IsSet()
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *GrantOut) HasExpiresAt() bool {
	if o != nil && o.ExpiresAt.IsSet() {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given NullableTime and assigns it to the ExpiresAt field.
func (o *GrantOut) SetExpiresAt(v time.Time) {
	o.ExpiresAt.Set(&v)
}
// SetExpiresAtNil sets the value for ExpiresAt to be an explicit nil
func (o *GrantOut) SetExpiresAtNil() {
	o.ExpiresAt.Set(nil)
}

// UnsetExpiresAt ensures that no value is present for ExpiresAt, not even an explicit nil
func (o *GrantOut) UnsetExpiresAt() {
	o.ExpiresAt.Unset()
}

// GetArtifactsAffected returns the ArtifactsAffected field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GrantOut) GetArtifactsAffected() int32 {
	if o == nil || IsNil(o.ArtifactsAffected.Get()) {
		var ret int32
		return ret
	}
	return *o.ArtifactsAffected.Get()
}

// GetArtifactsAffectedOk returns a tuple with the ArtifactsAffected field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GrantOut) GetArtifactsAffectedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ArtifactsAffected.Get(), o.ArtifactsAffected.IsSet()
}

// HasArtifactsAffected returns a boolean if a field has been set.
func (o *GrantOut) HasArtifactsAffected() bool {
	if o != nil && o.ArtifactsAffected.IsSet() {
		return true
	}

	return false
}

// SetArtifactsAffected gets a reference to the given NullableInt32 and assigns it to the ArtifactsAffected field.
func (o *GrantOut) SetArtifactsAffected(v int32) {
	o.ArtifactsAffected.Set(&v)
}
// SetArtifactsAffectedNil sets the value for ArtifactsAffected to be an explicit nil
func (o *GrantOut) SetArtifactsAffectedNil() {
	o.ArtifactsAffected.Set(nil)
}

// UnsetArtifactsAffected ensures that no value is present for ArtifactsAffected, not even an explicit nil
func (o *GrantOut) UnsetArtifactsAffected() {
	o.ArtifactsAffected.Unset()
}

func (o GrantOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GrantOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["resource_type"] = o.ResourceType
	toSerialize["resource_id"] = o.ResourceId
	toSerialize["principal_type"] = o.PrincipalType
	if o.PrincipalId.IsSet() {
		toSerialize["principal_id"] = o.PrincipalId.Get()
	}
	if o.PrincipalEmail.IsSet() {
		toSerialize["principal_email"] = o.PrincipalEmail.Get()
	}
	toSerialize["role"] = o.Role
	toSerialize["granted_by_type"] = o.GrantedByType
	toSerialize["granted_by_id"] = o.GrantedById
	if o.OnBehalfOf.IsSet() {
		toSerialize["on_behalf_of"] = o.OnBehalfOf.Get()
	}
	toSerialize["created_at"] = o.CreatedAt
	if o.ExpiresAt.IsSet() {
		toSerialize["expires_at"] = o.ExpiresAt.Get()
	}
	if o.ArtifactsAffected.IsSet() {
		toSerialize["artifacts_affected"] = o.ArtifactsAffected.Get()
	}
	return toSerialize, nil
}

func (o *GrantOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"resource_type",
		"resource_id",
		"principal_type",
		"role",
		"granted_by_type",
		"granted_by_id",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGrantOut := _GrantOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGrantOut)

	if err != nil {
		return err
	}

	*o = GrantOut(varGrantOut)

	return err
}

type NullableGrantOut struct {
	value *GrantOut
	isSet bool
}

func (v NullableGrantOut) Get() *GrantOut {
	return v.value
}

func (v *NullableGrantOut) Set(val *GrantOut) {
	v.value = val
	v.isSet = true
}

func (v NullableGrantOut) IsSet() bool {
	return v.isSet
}

func (v *NullableGrantOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGrantOut(val *GrantOut) *NullableGrantOut {
	return &NullableGrantOut{value: val, isSet: true}
}

func (v NullableGrantOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGrantOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


