/*
AgentDrive

AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agentdrive

import (
	"encoding/json"
)

// checks if the LinkIn type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LinkIn{}

// LinkIn struct for LinkIn
type LinkIn struct {
	Password NullableString `json:"password,omitempty"`
	ExpiresIn NullableInt32 `json:"expires_in,omitempty"`
}

// NewLinkIn instantiates a new LinkIn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLinkIn() *LinkIn {
	this := LinkIn{}
	return &this
}

// NewLinkInWithDefaults instantiates a new LinkIn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLinkInWithDefaults() *LinkIn {
	this := LinkIn{}
	return &this
}

// GetPassword returns the Password field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LinkIn) GetPassword() string {
	if o == nil || IsNil(o.Password.Get()) {
		var ret string
		return ret
	}
	return *o.Password.Get()
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LinkIn) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Password.Get(), o.Password.IsSet()
}

// HasPassword returns a boolean if a field has been set.
func (o *LinkIn) HasPassword() bool {
	if o != nil && o.Password.IsSet() {
		return true
	}

	return false
}

// SetPassword gets a reference to the given NullableString and assigns it to the Password field.
func (o *LinkIn) SetPassword(v string) {
	o.Password.Set(&v)
}
// SetPasswordNil sets the value for Password to be an explicit nil
func (o *LinkIn) SetPasswordNil() {
	o.Password.Set(nil)
}

// UnsetPassword ensures that no value is present for Password, not even an explicit nil
func (o *LinkIn) UnsetPassword() {
	o.Password.Unset()
}

// GetExpiresIn returns the ExpiresIn field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LinkIn) GetExpiresIn() int32 {
	if o == nil || IsNil(o.ExpiresIn.Get()) {
		var ret int32
		return ret
	}
	return *o.ExpiresIn.Get()
}

// GetExpiresInOk returns a tuple with the ExpiresIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LinkIn) GetExpiresInOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpiresIn.Get(), o.ExpiresIn.IsSet()
}

// HasExpiresIn returns a boolean if a field has been set.
func (o *LinkIn) HasExpiresIn() bool {
	if o != nil && o.ExpiresIn.IsSet() {
		return true
	}

	return false
}

// SetExpiresIn gets a reference to the given NullableInt32 and assigns it to the ExpiresIn field.
func (o *LinkIn) SetExpiresIn(v int32) {
	o.ExpiresIn.Set(&v)
}
// SetExpiresInNil sets the value for ExpiresIn to be an explicit nil
func (o *LinkIn) SetExpiresInNil() {
	o.ExpiresIn.Set(nil)
}

// UnsetExpiresIn ensures that no value is present for ExpiresIn, not even an explicit nil
func (o *LinkIn) UnsetExpiresIn() {
	o.ExpiresIn.Unset()
}

func (o LinkIn) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LinkIn) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Password.IsSet() {
		toSerialize["password"] = o.Password.Get()
	}
	if o.ExpiresIn.IsSet() {
		toSerialize["expires_in"] = o.ExpiresIn.Get()
	}
	return toSerialize, nil
}

type NullableLinkIn struct {
	value *LinkIn
	isSet bool
}

func (v NullableLinkIn) Get() *LinkIn {
	return v.value
}

func (v *NullableLinkIn) Set(val *LinkIn) {
	v.value = val
	v.isSet = true
}

func (v NullableLinkIn) IsSet() bool {
	return v.isSet
}

func (v *NullableLinkIn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLinkIn(val *LinkIn) *NullableLinkIn {
	return &NullableLinkIn{value: val, isSet: true}
}

func (v NullableLinkIn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLinkIn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


