/*
AgentDrive

AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agentdrive

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PublicIn type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PublicIn{}

// PublicIn struct for PublicIn
type PublicIn struct {
	Public bool `json:"public"`
}

type _PublicIn PublicIn

// NewPublicIn instantiates a new PublicIn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublicIn(public bool) *PublicIn {
	this := PublicIn{}
	this.Public = public
	return &this
}

// NewPublicInWithDefaults instantiates a new PublicIn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublicInWithDefaults() *PublicIn {
	this := PublicIn{}
	return &this
}

// GetPublic returns the Public field value
func (o *PublicIn) GetPublic() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Public
}

// GetPublicOk returns a tuple with the Public field value
// and a boolean to check if the value has been set.
func (o *PublicIn) GetPublicOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Public, true
}

// SetPublic sets field value
func (o *PublicIn) SetPublic(v bool) {
	o.Public = v
}

func (o PublicIn) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PublicIn) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["public"] = o.Public
	return toSerialize, nil
}

func (o *PublicIn) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"public",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPublicIn := _PublicIn{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPublicIn)

	if err != nil {
		return err
	}

	*o = PublicIn(varPublicIn)

	return err
}

type NullablePublicIn struct {
	value *PublicIn
	isSet bool
}

func (v NullablePublicIn) Get() *PublicIn {
	return v.value
}

func (v *NullablePublicIn) Set(val *PublicIn) {
	v.value = val
	v.isSet = true
}

func (v NullablePublicIn) IsSet() bool {
	return v.isSet
}

func (v *NullablePublicIn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublicIn(val *PublicIn) *NullablePublicIn {
	return &NullablePublicIn{value: val, isSet: true}
}

func (v NullablePublicIn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublicIn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


