/*
AgentDrive

AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agentdrive

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the FolderOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FolderOut{}

// FolderOut Folder resource (folders+permalinks design §13). `path` is the canonical leading+trailing-slash form; `share_key` is reserved metadata held now and wired by the render layer in v1.1.
type FolderOut struct {
	Id string `json:"id"`
	DriveId string `json:"drive_id"`
	Path string `json:"path"`
	Description NullableString `json:"description,omitempty"`
	Visibility NullableString `json:"visibility,omitempty"`
	ShareKey NullableString `json:"share_key,omitempty"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	DeletedAt NullableTime `json:"deleted_at,omitempty"`
	PurgeAt NullableTime `json:"purge_at,omitempty"`
}

type _FolderOut FolderOut

// NewFolderOut instantiates a new FolderOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFolderOut(id string, driveId string, path string, createdAt time.Time, updatedAt time.Time) *FolderOut {
	this := FolderOut{}
	this.Id = id
	this.DriveId = driveId
	this.Path = path
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewFolderOutWithDefaults instantiates a new FolderOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFolderOutWithDefaults() *FolderOut {
	this := FolderOut{}
	return &this
}

// GetId returns the Id field value
func (o *FolderOut) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *FolderOut) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *FolderOut) SetId(v string) {
	o.Id = v
}

// GetDriveId returns the DriveId field value
func (o *FolderOut) GetDriveId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DriveId
}

// GetDriveIdOk returns a tuple with the DriveId field value
// and a boolean to check if the value has been set.
func (o *FolderOut) GetDriveIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DriveId, true
}

// SetDriveId sets field value
func (o *FolderOut) SetDriveId(v string) {
	o.DriveId = v
}

// GetPath returns the Path field value
func (o *FolderOut) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *FolderOut) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *FolderOut) SetPath(v string) {
	o.Path = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FolderOut) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FolderOut) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *FolderOut) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *FolderOut) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *FolderOut) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *FolderOut) UnsetDescription() {
	o.Description.Unset()
}

// GetVisibility returns the Visibility field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FolderOut) GetVisibility() string {
	if o == nil || IsNil(o.Visibility.Get()) {
		var ret string
		return ret
	}
	return *o.Visibility.Get()
}

// GetVisibilityOk returns a tuple with the Visibility field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FolderOut) GetVisibilityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Visibility.Get(), o.Visibility.IsSet()
}

// HasVisibility returns a boolean if a field has been set.
func (o *FolderOut) HasVisibility() bool {
	if o != nil && o.Visibility.IsSet() {
		return true
	}

	return false
}

// SetVisibility gets a reference to the given NullableString and assigns it to the Visibility field.
func (o *FolderOut) SetVisibility(v string) {
	o.Visibility.Set(&v)
}
// SetVisibilityNil sets the value for Visibility to be an explicit nil
func (o *FolderOut) SetVisibilityNil() {
	o.Visibility.Set(nil)
}

// UnsetVisibility ensures that no value is present for Visibility, not even an explicit nil
func (o *FolderOut) UnsetVisibility() {
	o.Visibility.Unset()
}

// GetShareKey returns the ShareKey field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FolderOut) GetShareKey() string {
	if o == nil || IsNil(o.ShareKey.Get()) {
		var ret string
		return ret
	}
	return *o.ShareKey.Get()
}

// GetShareKeyOk returns a tuple with the ShareKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FolderOut) GetShareKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ShareKey.Get(), o.ShareKey.IsSet()
}

// HasShareKey returns a boolean if a field has been set.
func (o *FolderOut) HasShareKey() bool {
	if o != nil && o.ShareKey.IsSet() {
		return true
	}

	return false
}

// SetShareKey gets a reference to the given NullableString and assigns it to the ShareKey field.
func (o *FolderOut) SetShareKey(v string) {
	o.ShareKey.Set(&v)
}
// SetShareKeyNil sets the value for ShareKey to be an explicit nil
func (o *FolderOut) SetShareKeyNil() {
	o.ShareKey.Set(nil)
}

// UnsetShareKey ensures that no value is present for ShareKey, not even an explicit nil
func (o *FolderOut) UnsetShareKey() {
	o.ShareKey.Unset()
}

// GetCreatedAt returns the CreatedAt field value
func (o *FolderOut) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *FolderOut) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *FolderOut) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *FolderOut) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *FolderOut) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *FolderOut) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetDeletedAt returns the DeletedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FolderOut) GetDeletedAt() time.Time {
	if o == nil || IsNil(o.DeletedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.DeletedAt.Get()
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FolderOut) GetDeletedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeletedAt.Get(), o.DeletedAt.IsSet()
}

// HasDeletedAt returns a boolean if a field has been set.
func (o *FolderOut) HasDeletedAt() bool {
	if o != nil && o.DeletedAt.IsSet() {
		return true
	}

	return false
}

// SetDeletedAt gets a reference to the given NullableTime and assigns it to the DeletedAt field.
func (o *FolderOut) SetDeletedAt(v time.Time) {
	o.DeletedAt.Set(&v)
}
// SetDeletedAtNil sets the value for DeletedAt to be an explicit nil
func (o *FolderOut) SetDeletedAtNil() {
	o.DeletedAt.Set(nil)
}

// UnsetDeletedAt ensures that no value is present for DeletedAt, not even an explicit nil
func (o *FolderOut) UnsetDeletedAt() {
	o.DeletedAt.Unset()
}

// GetPurgeAt returns the PurgeAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FolderOut) GetPurgeAt() time.Time {
	if o == nil || IsNil(o.PurgeAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.PurgeAt.Get()
}

// GetPurgeAtOk returns a tuple with the PurgeAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FolderOut) GetPurgeAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.PurgeAt.Get(), o.PurgeAt.IsSet()
}

// HasPurgeAt returns a boolean if a field has been set.
func (o *FolderOut) HasPurgeAt() bool {
	if o != nil && o.PurgeAt.IsSet() {
		return true
	}

	return false
}

// SetPurgeAt gets a reference to the given NullableTime and assigns it to the PurgeAt field.
func (o *FolderOut) SetPurgeAt(v time.Time) {
	o.PurgeAt.Set(&v)
}
// SetPurgeAtNil sets the value for PurgeAt to be an explicit nil
func (o *FolderOut) SetPurgeAtNil() {
	o.PurgeAt.Set(nil)
}

// UnsetPurgeAt ensures that no value is present for PurgeAt, not even an explicit nil
func (o *FolderOut) UnsetPurgeAt() {
	o.PurgeAt.Unset()
}

func (o FolderOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FolderOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["drive_id"] = o.DriveId
	toSerialize["path"] = o.Path
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.Visibility.IsSet() {
		toSerialize["visibility"] = o.Visibility.Get()
	}
	if o.ShareKey.IsSet() {
		toSerialize["share_key"] = o.ShareKey.Get()
	}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	if o.DeletedAt.IsSet() {
		toSerialize["deleted_at"] = o.DeletedAt.Get()
	}
	if o.PurgeAt.IsSet() {
		toSerialize["purge_at"] = o.PurgeAt.Get()
	}
	return toSerialize, nil
}

func (o *FolderOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"drive_id",
		"path",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFolderOut := _FolderOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFolderOut)

	if err != nil {
		return err
	}

	*o = FolderOut(varFolderOut)

	return err
}

type NullableFolderOut struct {
	value *FolderOut
	isSet bool
}

func (v NullableFolderOut) Get() *FolderOut {
	return v.value
}

func (v *NullableFolderOut) Set(val *FolderOut) {
	v.value = val
	v.isSet = true
}

func (v NullableFolderOut) IsSet() bool {
	return v.isSet
}

func (v *NullableFolderOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFolderOut(val *FolderOut) *NullableFolderOut {
	return &NullableFolderOut{value: val, isSet: true}
}

func (v NullableFolderOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFolderOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


