/*
AgentDrive

AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agentdrive

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RenameIn type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RenameIn{}

// RenameIn PATCH /v0/artifacts/{art_id} body — rename / move.
type RenameIn struct {
	Path string `json:"path"`
}

type _RenameIn RenameIn

// NewRenameIn instantiates a new RenameIn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRenameIn(path string) *RenameIn {
	this := RenameIn{}
	this.Path = path
	return &this
}

// NewRenameInWithDefaults instantiates a new RenameIn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRenameInWithDefaults() *RenameIn {
	this := RenameIn{}
	return &this
}

// GetPath returns the Path field value
func (o *RenameIn) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *RenameIn) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *RenameIn) SetPath(v string) {
	o.Path = v
}

func (o RenameIn) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RenameIn) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["path"] = o.Path
	return toSerialize, nil
}

func (o *RenameIn) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"path",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRenameIn := _RenameIn{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRenameIn)

	if err != nil {
		return err
	}

	*o = RenameIn(varRenameIn)

	return err
}

type NullableRenameIn struct {
	value *RenameIn
	isSet bool
}

func (v NullableRenameIn) Get() *RenameIn {
	return v.value
}

func (v *NullableRenameIn) Set(val *RenameIn) {
	v.value = val
	v.isSet = true
}

func (v NullableRenameIn) IsSet() bool {
	return v.isSet
}

func (v *NullableRenameIn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRenameIn(val *RenameIn) *NullableRenameIn {
	return &NullableRenameIn{value: val, isSet: true}
}

func (v NullableRenameIn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRenameIn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


