/*
AgentDrive

AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agentdrive

import (
	"encoding/json"
)

// checks if the FolderPatchIn type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FolderPatchIn{}

// FolderPatchIn PATCH /v0/folders/{fld_id} body — partial update. Field absence = unchanged; explicit None = clear field.
type FolderPatchIn struct {
	Description NullableString `json:"description,omitempty"`
	Visibility NullableString `json:"visibility,omitempty"`
}

// NewFolderPatchIn instantiates a new FolderPatchIn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFolderPatchIn() *FolderPatchIn {
	this := FolderPatchIn{}
	return &this
}

// NewFolderPatchInWithDefaults instantiates a new FolderPatchIn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFolderPatchInWithDefaults() *FolderPatchIn {
	this := FolderPatchIn{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FolderPatchIn) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FolderPatchIn) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *FolderPatchIn) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *FolderPatchIn) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *FolderPatchIn) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *FolderPatchIn) UnsetDescription() {
	o.Description.Unset()
}

// GetVisibility returns the Visibility field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FolderPatchIn) GetVisibility() string {
	if o == nil || IsNil(o.Visibility.Get()) {
		var ret string
		return ret
	}
	return *o.Visibility.Get()
}

// GetVisibilityOk returns a tuple with the Visibility field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FolderPatchIn) GetVisibilityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Visibility.Get(), o.Visibility.IsSet()
}

// HasVisibility returns a boolean if a field has been set.
func (o *FolderPatchIn) HasVisibility() bool {
	if o != nil && o.Visibility.IsSet() {
		return true
	}

	return false
}

// SetVisibility gets a reference to the given NullableString and assigns it to the Visibility field.
func (o *FolderPatchIn) SetVisibility(v string) {
	o.Visibility.Set(&v)
}
// SetVisibilityNil sets the value for Visibility to be an explicit nil
func (o *FolderPatchIn) SetVisibilityNil() {
	o.Visibility.Set(nil)
}

// UnsetVisibility ensures that no value is present for Visibility, not even an explicit nil
func (o *FolderPatchIn) UnsetVisibility() {
	o.Visibility.Unset()
}

func (o FolderPatchIn) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FolderPatchIn) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.Visibility.IsSet() {
		toSerialize["visibility"] = o.Visibility.Get()
	}
	return toSerialize, nil
}

type NullableFolderPatchIn struct {
	value *FolderPatchIn
	isSet bool
}

func (v NullableFolderPatchIn) Get() *FolderPatchIn {
	return v.value
}

func (v *NullableFolderPatchIn) Set(val *FolderPatchIn) {
	v.value = val
	v.isSet = true
}

func (v NullableFolderPatchIn) IsSet() bool {
	return v.isSet
}

func (v *NullableFolderPatchIn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFolderPatchIn(val *FolderPatchIn) *NullableFolderPatchIn {
	return &NullableFolderPatchIn{value: val, isSet: true}
}

func (v NullableFolderPatchIn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFolderPatchIn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


