/*
AgentDrive

AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agentdrive

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the UserTokenOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UserTokenOut{}

// UserTokenOut One `ad_user_` token — metadata only. The raw token is NEVER exposed over the API (minting is web-only, reveal-once); this shape omits both the raw value and the stored hash by construction.
type UserTokenOut struct {
	Id string `json:"id"`
	Prefix string `json:"prefix"`
	Label NullableString `json:"label"`
	Scope string `json:"scope"`
	DefaultDriveId NullableString `json:"default_drive_id"`
	LastUsedAt NullableTime `json:"last_used_at"`
	ExpiresAt NullableTime `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
	RevokedAt NullableTime `json:"revoked_at"`
}

type _UserTokenOut UserTokenOut

// NewUserTokenOut instantiates a new UserTokenOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserTokenOut(id string, prefix string, label NullableString, scope string, defaultDriveId NullableString, lastUsedAt NullableTime, expiresAt NullableTime, createdAt time.Time, revokedAt NullableTime) *UserTokenOut {
	this := UserTokenOut{}
	this.Id = id
	this.Prefix = prefix
	this.Label = label
	this.Scope = scope
	this.DefaultDriveId = defaultDriveId
	this.LastUsedAt = lastUsedAt
	this.ExpiresAt = expiresAt
	this.CreatedAt = createdAt
	this.RevokedAt = revokedAt
	return &this
}

// NewUserTokenOutWithDefaults instantiates a new UserTokenOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserTokenOutWithDefaults() *UserTokenOut {
	this := UserTokenOut{}
	return &this
}

// GetId returns the Id field value
func (o *UserTokenOut) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UserTokenOut) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UserTokenOut) SetId(v string) {
	o.Id = v
}

// GetPrefix returns the Prefix field value
func (o *UserTokenOut) GetPrefix() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Prefix
}

// GetPrefixOk returns a tuple with the Prefix field value
// and a boolean to check if the value has been set.
func (o *UserTokenOut) GetPrefixOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Prefix, true
}

// SetPrefix sets field value
func (o *UserTokenOut) SetPrefix(v string) {
	o.Prefix = v
}

// GetLabel returns the Label field value
// If the value is explicit nil, the zero value for string will be returned
func (o *UserTokenOut) GetLabel() string {
	if o == nil || o.Label.Get() == nil {
		var ret string
		return ret
	}

	return *o.Label.Get()
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserTokenOut) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Label.Get(), o.Label.IsSet()
}

// SetLabel sets field value
func (o *UserTokenOut) SetLabel(v string) {
	o.Label.Set(&v)
}

// GetScope returns the Scope field value
func (o *UserTokenOut) GetScope() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Scope
}

// GetScopeOk returns a tuple with the Scope field value
// and a boolean to check if the value has been set.
func (o *UserTokenOut) GetScopeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Scope, true
}

// SetScope sets field value
func (o *UserTokenOut) SetScope(v string) {
	o.Scope = v
}

// GetDefaultDriveId returns the DefaultDriveId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *UserTokenOut) GetDefaultDriveId() string {
	if o == nil || o.DefaultDriveId.Get() == nil {
		var ret string
		return ret
	}

	return *o.DefaultDriveId.Get()
}

// GetDefaultDriveIdOk returns a tuple with the DefaultDriveId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserTokenOut) GetDefaultDriveIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DefaultDriveId.Get(), o.DefaultDriveId.IsSet()
}

// SetDefaultDriveId sets field value
func (o *UserTokenOut) SetDefaultDriveId(v string) {
	o.DefaultDriveId.Set(&v)
}

// GetLastUsedAt returns the LastUsedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *UserTokenOut) GetLastUsedAt() time.Time {
	if o == nil || o.LastUsedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.LastUsedAt.Get()
}

// GetLastUsedAtOk returns a tuple with the LastUsedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserTokenOut) GetLastUsedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastUsedAt.Get(), o.LastUsedAt.IsSet()
}

// SetLastUsedAt sets field value
func (o *UserTokenOut) SetLastUsedAt(v time.Time) {
	o.LastUsedAt.Set(&v)
}

// GetExpiresAt returns the ExpiresAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *UserTokenOut) GetExpiresAt() time.Time {
	if o == nil || o.ExpiresAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.ExpiresAt.Get()
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserTokenOut) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpiresAt.Get(), o.ExpiresAt.IsSet()
}

// SetExpiresAt sets field value
func (o *UserTokenOut) SetExpiresAt(v time.Time) {
	o.ExpiresAt.Set(&v)
}

// GetCreatedAt returns the CreatedAt field value
func (o *UserTokenOut) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *UserTokenOut) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *UserTokenOut) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetRevokedAt returns the RevokedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *UserTokenOut) GetRevokedAt() time.Time {
	if o == nil || o.RevokedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.RevokedAt.Get()
}

// GetRevokedAtOk returns a tuple with the RevokedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserTokenOut) GetRevokedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.RevokedAt.Get(), o.RevokedAt.IsSet()
}

// SetRevokedAt sets field value
func (o *UserTokenOut) SetRevokedAt(v time.Time) {
	o.RevokedAt.Set(&v)
}

func (o UserTokenOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UserTokenOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["prefix"] = o.Prefix
	toSerialize["label"] = o.Label.Get()
	toSerialize["scope"] = o.Scope
	toSerialize["default_drive_id"] = o.DefaultDriveId.Get()
	toSerialize["last_used_at"] = o.LastUsedAt.Get()
	toSerialize["expires_at"] = o.ExpiresAt.Get()
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["revoked_at"] = o.RevokedAt.Get()
	return toSerialize, nil
}

func (o *UserTokenOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"prefix",
		"label",
		"scope",
		"default_drive_id",
		"last_used_at",
		"expires_at",
		"created_at",
		"revoked_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUserTokenOut := _UserTokenOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUserTokenOut)

	if err != nil {
		return err
	}

	*o = UserTokenOut(varUserTokenOut)

	return err
}

type NullableUserTokenOut struct {
	value *UserTokenOut
	isSet bool
}

func (v NullableUserTokenOut) Get() *UserTokenOut {
	return v.value
}

func (v *NullableUserTokenOut) Set(val *UserTokenOut) {
	v.value = val
	v.isSet = true
}

func (v NullableUserTokenOut) IsSet() bool {
	return v.isSet
}

func (v *NullableUserTokenOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserTokenOut(val *UserTokenOut) *NullableUserTokenOut {
	return &NullableUserTokenOut{value: val, isSet: true}
}

func (v NullableUserTokenOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserTokenOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


