/*
AgentDrive

AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agentdrive

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DriveKeyRotateOut type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DriveKeyRotateOut{}

// DriveKeyRotateOut POST /v0/drives/{id}/keys/rotate response — the rotated drive's new `ad_live_` key, reveal-once. The old key is invalidated immediately.
type DriveKeyRotateOut struct {
	Id string `json:"id"`
	ApiKey string `json:"api_key"`
}

type _DriveKeyRotateOut DriveKeyRotateOut

// NewDriveKeyRotateOut instantiates a new DriveKeyRotateOut object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDriveKeyRotateOut(id string, apiKey string) *DriveKeyRotateOut {
	this := DriveKeyRotateOut{}
	this.Id = id
	this.ApiKey = apiKey
	return &this
}

// NewDriveKeyRotateOutWithDefaults instantiates a new DriveKeyRotateOut object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDriveKeyRotateOutWithDefaults() *DriveKeyRotateOut {
	this := DriveKeyRotateOut{}
	return &this
}

// GetId returns the Id field value
func (o *DriveKeyRotateOut) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DriveKeyRotateOut) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DriveKeyRotateOut) SetId(v string) {
	o.Id = v
}

// GetApiKey returns the ApiKey field value
func (o *DriveKeyRotateOut) GetApiKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApiKey
}

// GetApiKeyOk returns a tuple with the ApiKey field value
// and a boolean to check if the value has been set.
func (o *DriveKeyRotateOut) GetApiKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiKey, true
}

// SetApiKey sets field value
func (o *DriveKeyRotateOut) SetApiKey(v string) {
	o.ApiKey = v
}

func (o DriveKeyRotateOut) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DriveKeyRotateOut) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["api_key"] = o.ApiKey
	return toSerialize, nil
}

func (o *DriveKeyRotateOut) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"api_key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDriveKeyRotateOut := _DriveKeyRotateOut{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDriveKeyRotateOut)

	if err != nil {
		return err
	}

	*o = DriveKeyRotateOut(varDriveKeyRotateOut)

	return err
}

type NullableDriveKeyRotateOut struct {
	value *DriveKeyRotateOut
	isSet bool
}

func (v NullableDriveKeyRotateOut) Get() *DriveKeyRotateOut {
	return v.value
}

func (v *NullableDriveKeyRotateOut) Set(val *DriveKeyRotateOut) {
	v.value = val
	v.isSet = true
}

func (v NullableDriveKeyRotateOut) IsSet() bool {
	return v.isSet
}

func (v *NullableDriveKeyRotateOut) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDriveKeyRotateOut(val *DriveKeyRotateOut) *NullableDriveKeyRotateOut {
	return &NullableDriveKeyRotateOut{value: val, isSet: true}
}

func (v NullableDriveKeyRotateOut) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDriveKeyRotateOut) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


