/*
AgentDrive

AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agentdrive

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GrantIn type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GrantIn{}

// GrantIn struct for GrantIn
type GrantIn struct {
	Principal string `json:"principal"`
	Role *string `json:"role,omitempty"`
}

type _GrantIn GrantIn

// NewGrantIn instantiates a new GrantIn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGrantIn(principal string) *GrantIn {
	this := GrantIn{}
	this.Principal = principal
	var role string = "viewer"
	this.Role = &role
	return &this
}

// NewGrantInWithDefaults instantiates a new GrantIn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGrantInWithDefaults() *GrantIn {
	this := GrantIn{}
	var role string = "viewer"
	this.Role = &role
	return &this
}

// GetPrincipal returns the Principal field value
func (o *GrantIn) GetPrincipal() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Principal
}

// GetPrincipalOk returns a tuple with the Principal field value
// and a boolean to check if the value has been set.
func (o *GrantIn) GetPrincipalOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Principal, true
}

// SetPrincipal sets field value
func (o *GrantIn) SetPrincipal(v string) {
	o.Principal = v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *GrantIn) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GrantIn) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *GrantIn) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *GrantIn) SetRole(v string) {
	o.Role = &v
}

func (o GrantIn) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GrantIn) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["principal"] = o.Principal
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	return toSerialize, nil
}

func (o *GrantIn) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"principal",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGrantIn := _GrantIn{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGrantIn)

	if err != nil {
		return err
	}

	*o = GrantIn(varGrantIn)

	return err
}

type NullableGrantIn struct {
	value *GrantIn
	isSet bool
}

func (v NullableGrantIn) Get() *GrantIn {
	return v.value
}

func (v *NullableGrantIn) Set(val *GrantIn) {
	v.value = val
	v.isSet = true
}

func (v NullableGrantIn) IsSet() bool {
	return v.isSet
}

func (v *NullableGrantIn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGrantIn(val *GrantIn) *NullableGrantIn {
	return &NullableGrantIn{value: val, isSet: true}
}

func (v NullableGrantIn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGrantIn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


