/*
AgentDrive

AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package agentdrive

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SearchPage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchPage{}

// SearchPage struct for SearchPage
type SearchPage struct {
	Items []SearchHitOut `json:"items"`
	NextCursor NullableString `json:"next_cursor,omitempty"`
}

type _SearchPage SearchPage

// NewSearchPage instantiates a new SearchPage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchPage(items []SearchHitOut) *SearchPage {
	this := SearchPage{}
	this.Items = items
	return &this
}

// NewSearchPageWithDefaults instantiates a new SearchPage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchPageWithDefaults() *SearchPage {
	this := SearchPage{}
	return &this
}

// GetItems returns the Items field value
func (o *SearchPage) GetItems() []SearchHitOut {
	if o == nil {
		var ret []SearchHitOut
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *SearchPage) GetItemsOk() ([]SearchHitOut, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *SearchPage) SetItems(v []SearchHitOut) {
	o.Items = v
}

// GetNextCursor returns the NextCursor field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SearchPage) GetNextCursor() string {
	if o == nil || IsNil(o.NextCursor.Get()) {
		var ret string
		return ret
	}
	return *o.NextCursor.Get()
}

// GetNextCursorOk returns a tuple with the NextCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SearchPage) GetNextCursorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextCursor.Get(), o.NextCursor.IsSet()
}

// HasNextCursor returns a boolean if a field has been set.
func (o *SearchPage) HasNextCursor() bool {
	if o != nil && o.NextCursor.IsSet() {
		return true
	}

	return false
}

// SetNextCursor gets a reference to the given NullableString and assigns it to the NextCursor field.
func (o *SearchPage) SetNextCursor(v string) {
	o.NextCursor.Set(&v)
}
// SetNextCursorNil sets the value for NextCursor to be an explicit nil
func (o *SearchPage) SetNextCursorNil() {
	o.NextCursor.Set(nil)
}

// UnsetNextCursor ensures that no value is present for NextCursor, not even an explicit nil
func (o *SearchPage) UnsetNextCursor() {
	o.NextCursor.Unset()
}

func (o SearchPage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchPage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	if o.NextCursor.IsSet() {
		toSerialize["next_cursor"] = o.NextCursor.Get()
	}
	return toSerialize, nil
}

func (o *SearchPage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSearchPage := _SearchPage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSearchPage)

	if err != nil {
		return err
	}

	*o = SearchPage(varSearchPage)

	return err
}

type NullableSearchPage struct {
	value *SearchPage
	isSet bool
}

func (v NullableSearchPage) Get() *SearchPage {
	return v.value
}

func (v *NullableSearchPage) Set(val *SearchPage) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchPage) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchPage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchPage(val *SearchPage) *NullableSearchPage {
	return &NullableSearchPage{value: val, isSet: true}
}

func (v NullableSearchPage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchPage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


