/* tslint:disable */
/* eslint-disable */
/**
 * AgentDrive
 * AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClaimInitResponse
 */
export interface ClaimInitResponse {
    /**
     * Per-attempt opaque token; the agent does not need to present it.
     * @type {string}
     * @memberof ClaimInitResponse
     */
    claimAttemptToken: string;
    /**
     * Human-readable code the user types/sees on /claim.
     * @type {string}
     * @memberof ClaimInitResponse
     */
    userCode: string;
    /**
     * URL to direct the human to.
     * @type {string}
     * @memberof ClaimInitResponse
     */
    verificationUri: string;
    /**
     * Convenience: same as `verification_uri` but with the user_code pre-baked so the human doesn't have to type it. RFC 8628 idiom.
     * @type {string}
     * @memberof ClaimInitResponse
     */
    verificationUriComplete: string;
    /**
     * 
     * @type {Date}
     * @memberof ClaimInitResponse
     */
    expiresAt: Date;
}

/**
 * Check if a given object implements the ClaimInitResponse interface.
 */
export function instanceOfClaimInitResponse(value: object): value is ClaimInitResponse {
    if ((!('claimAttemptToken' in value) && !('claim_attempt_token' in value)) || (value['claimAttemptToken'] === undefined && value['claim_attempt_token'] === undefined)) return false;
    if ((!('userCode' in value) && !('user_code' in value)) || (value['userCode'] === undefined && value['user_code'] === undefined)) return false;
    if ((!('verificationUri' in value) && !('verification_uri' in value)) || (value['verificationUri'] === undefined && value['verification_uri'] === undefined)) return false;
    if ((!('verificationUriComplete' in value) && !('verification_uri_complete' in value)) || (value['verificationUriComplete'] === undefined && value['verification_uri_complete'] === undefined)) return false;
    if ((!('expiresAt' in value) && !('expires_at' in value)) || (value['expiresAt'] === undefined && value['expires_at'] === undefined)) return false;
    return true;
}

export function ClaimInitResponseFromJSON(json: any): ClaimInitResponse {
    return ClaimInitResponseFromJSONTyped(json, false);
}

export function ClaimInitResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClaimInitResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'claimAttemptToken': json['claim_attempt_token'],
        'userCode': json['user_code'],
        'verificationUri': json['verification_uri'],
        'verificationUriComplete': json['verification_uri_complete'],
        'expiresAt': (new Date(json['expires_at'])),
    };
}

export function ClaimInitResponseToJSON(json: any): ClaimInitResponse {
    return ClaimInitResponseToJSONTyped(json, false);
}

export function ClaimInitResponseToJSONTyped(value?: ClaimInitResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'claim_attempt_token': value['claimAttemptToken'],
        'user_code': value['userCode'],
        'verification_uri': value['verificationUri'],
        'verification_uri_complete': value['verificationUriComplete'],
        'expires_at': value['expiresAt'].toISOString(),
    };
}

