/* tslint:disable */
/* eslint-disable */
/**
 * AgentDrive
 * AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CompileOptions } from './CompileOptions';
import {
    CompileOptionsFromJSON,
    CompileOptionsFromJSONTyped,
    CompileOptionsToJSON,
    CompileOptionsToJSONTyped,
} from './CompileOptions';

/**
 * 
 * @export
 * @interface CompileJobIn
 */
export interface CompileJobIn {
    /**
     * 
     * @type {string}
     * @memberof CompileJobIn
     */
    task?: string;
    /**
     * 
     * @type {CompileOptions}
     * @memberof CompileJobIn
     */
    options?: CompileOptions;
}

/**
 * Check if a given object implements the CompileJobIn interface.
 */
export function instanceOfCompileJobIn(value: object): value is CompileJobIn {
    return true;
}

export function CompileJobInFromJSON(json: any): CompileJobIn {
    return CompileJobInFromJSONTyped(json, false);
}

export function CompileJobInFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompileJobIn {
    if (json == null) {
        return json;
    }
    return {
        
        'task': json['task'] == null ? undefined : json['task'],
        'options': json['options'] == null ? undefined : CompileOptionsFromJSON(json['options']),
    };
}

export function CompileJobInToJSON(json: any): CompileJobIn {
    return CompileJobInToJSONTyped(json, false);
}

export function CompileJobInToJSONTyped(value?: CompileJobIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'task': value['task'],
        'options': CompileOptionsToJSON(value['options']),
    };
}

