/* tslint:disable */
/* eslint-disable */
/**
 * AgentDrive
 * AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * POST /v0/drives/{id}/keys/rotate response — the rotated drive's new
 * `ad_live_` key, reveal-once. The old key is invalidated immediately.
 * @export
 * @interface DriveKeyRotateOut
 */
export interface DriveKeyRotateOut {
    /**
     * 
     * @type {string}
     * @memberof DriveKeyRotateOut
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof DriveKeyRotateOut
     */
    apiKey: string;
}

/**
 * Check if a given object implements the DriveKeyRotateOut interface.
 */
export function instanceOfDriveKeyRotateOut(value: object): value is DriveKeyRotateOut {
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('apiKey' in value) && !('api_key' in value)) || (value['apiKey'] === undefined && value['api_key'] === undefined)) return false;
    return true;
}

export function DriveKeyRotateOutFromJSON(json: any): DriveKeyRotateOut {
    return DriveKeyRotateOutFromJSONTyped(json, false);
}

export function DriveKeyRotateOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): DriveKeyRotateOut {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'apiKey': json['api_key'],
    };
}

export function DriveKeyRotateOutToJSON(json: any): DriveKeyRotateOut {
    return DriveKeyRotateOutToJSONTyped(json, false);
}

export function DriveKeyRotateOutToJSONTyped(value?: DriveKeyRotateOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'api_key': value['apiKey'],
    };
}

