/* tslint:disable */
/* eslint-disable */
/**
 * AgentDrive
 * AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * PATCH /v0/folders/{fld_id} body — partial update.
 * Field absence = unchanged; explicit None = clear field.
 * @export
 * @interface FolderPatchIn
 */
export interface FolderPatchIn {
    /**
     * 
     * @type {string}
     * @memberof FolderPatchIn
     */
    description?: string | null;
    /**
     * 
     * @type {FolderPatchInVisibilityEnum}
     * @memberof FolderPatchIn
     */
    visibility?: FolderPatchInVisibilityEnum | null;
}


/**
 * @export
 */
export const FolderPatchInVisibilityEnum = {
    Public: 'public',
    Private: 'private'
} as const;
export type FolderPatchInVisibilityEnum = typeof FolderPatchInVisibilityEnum[keyof typeof FolderPatchInVisibilityEnum];


/**
 * Check if a given object implements the FolderPatchIn interface.
 */
export function instanceOfFolderPatchIn(value: object): value is FolderPatchIn {
    return true;
}

export function FolderPatchInFromJSON(json: any): FolderPatchIn {
    return FolderPatchInFromJSONTyped(json, false);
}

export function FolderPatchInFromJSONTyped(json: any, ignoreDiscriminator: boolean): FolderPatchIn {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'visibility': json['visibility'] == null ? undefined : json['visibility'],
    };
}

export function FolderPatchInToJSON(json: any): FolderPatchIn {
    return FolderPatchInToJSONTyped(json, false);
}

export function FolderPatchInToJSONTyped(value?: FolderPatchIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'visibility': value['visibility'],
    };
}

