/* tslint:disable */
/* eslint-disable */
/**
 * AgentDrive
 * AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GrantIn
 */
export interface GrantIn {
    /**
     * 
     * @type {string}
     * @memberof GrantIn
     */
    principal: string;
    /**
     * 
     * @type {string}
     * @memberof GrantIn
     */
    role?: string;
}

/**
 * Check if a given object implements the GrantIn interface.
 */
export function instanceOfGrantIn(value: object): value is GrantIn {
    if (!('principal' in value) || value['principal'] === undefined) return false;
    return true;
}

export function GrantInFromJSON(json: any): GrantIn {
    return GrantInFromJSONTyped(json, false);
}

export function GrantInFromJSONTyped(json: any, ignoreDiscriminator: boolean): GrantIn {
    if (json == null) {
        return json;
    }
    return {
        
        'principal': json['principal'],
        'role': json['role'] == null ? undefined : json['role'],
    };
}

export function GrantInToJSON(json: any): GrantIn {
    return GrantInToJSONTyped(json, false);
}

export function GrantInToJSONTyped(value?: GrantIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'principal': value['principal'],
        'role': value['role'],
    };
}

