/* tslint:disable */
/* eslint-disable */
/**
 * AgentDrive
 * AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LookupValuesIn
 */
export interface LookupValuesIn {
    /**
     * 
     * @type {string}
     * @memberof LookupValuesIn
     */
    dataset: string;
    /**
     * 
     * @type {string}
     * @memberof LookupValuesIn
     */
    column: string;
    /**
     * 
     * @type {number}
     * @memberof LookupValuesIn
     */
    limit?: number;
}

/**
 * Check if a given object implements the LookupValuesIn interface.
 */
export function instanceOfLookupValuesIn(value: object): value is LookupValuesIn {
    if (!('dataset' in value) || value['dataset'] === undefined) return false;
    if (!('column' in value) || value['column'] === undefined) return false;
    return true;
}

export function LookupValuesInFromJSON(json: any): LookupValuesIn {
    return LookupValuesInFromJSONTyped(json, false);
}

export function LookupValuesInFromJSONTyped(json: any, ignoreDiscriminator: boolean): LookupValuesIn {
    if (json == null) {
        return json;
    }
    return {
        
        'dataset': json['dataset'],
        'column': json['column'],
        'limit': json['limit'] == null ? undefined : json['limit'],
    };
}

export function LookupValuesInToJSON(json: any): LookupValuesIn {
    return LookupValuesInToJSONTyped(json, false);
}

export function LookupValuesInToJSONTyped(value?: LookupValuesIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dataset': value['dataset'],
        'column': value['column'],
        'limit': value['limit'],
    };
}

