/* tslint:disable */
/* eslint-disable */
/**
 * AgentDrive
 * AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QueryIn
 */
export interface QueryIn {
    /**
     * 
     * @type {string}
     * @memberof QueryIn
     */
    sql: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof QueryIn
     */
    inputs?: { [key: string]: string; };
    /**
     * 
     * @type {boolean}
     * @memberof QueryIn
     */
    dryRun?: boolean;
}

/**
 * Check if a given object implements the QueryIn interface.
 */
export function instanceOfQueryIn(value: object): value is QueryIn {
    if (!('sql' in value) || value['sql'] === undefined) return false;
    return true;
}

export function QueryInFromJSON(json: any): QueryIn {
    return QueryInFromJSONTyped(json, false);
}

export function QueryInFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryIn {
    if (json == null) {
        return json;
    }
    return {
        
        'sql': json['sql'],
        'inputs': json['inputs'] == null ? undefined : json['inputs'],
        'dryRun': json['dry_run'] == null ? undefined : json['dry_run'],
    };
}

export function QueryInToJSON(json: any): QueryIn {
    return QueryInToJSONTyped(json, false);
}

export function QueryInToJSONTyped(value?: QueryIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sql': value['sql'],
        'inputs': value['inputs'],
        'dry_run': value['dryRun'],
    };
}

