/* tslint:disable */
/* eslint-disable */
/**
 * AgentDrive
 * AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * PATCH /v0/artifacts/{art_id} body — rename / move.
 * @export
 * @interface RenameIn
 */
export interface RenameIn {
    /**
     * 
     * @type {string}
     * @memberof RenameIn
     */
    path: string;
}

/**
 * Check if a given object implements the RenameIn interface.
 */
export function instanceOfRenameIn(value: object): value is RenameIn {
    if (!('path' in value) || value['path'] === undefined) return false;
    return true;
}

export function RenameInFromJSON(json: any): RenameIn {
    return RenameInFromJSONTyped(json, false);
}

export function RenameInFromJSONTyped(json: any, ignoreDiscriminator: boolean): RenameIn {
    if (json == null) {
        return json;
    }
    return {
        
        'path': json['path'],
    };
}

export function RenameInToJSON(json: any): RenameIn {
    return RenameInToJSONTyped(json, false);
}

export function RenameInToJSONTyped(value?: RenameIn | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'path': value['path'],
    };
}

