/* tslint:disable */
/* eslint-disable */
/**
 * AgentDrive
 * AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * `POST /oauth2/token` success response. Mirrors RFC 6749 with
 * an optional `identity_assertion` field for the claim grant path
 * (where a fresh post-claim assertion supersedes the pre-claim
 * one).
 * @export
 * @interface TokenResponse
 */
export interface TokenResponse {
    /**
     * 
     * @type {string}
     * @memberof TokenResponse
     */
    accessToken: string;
    /**
     * 
     * @type {string}
     * @memberof TokenResponse
     */
    tokenType?: string;
    /**
     * Seconds until access_token expiry.
     * @type {number}
     * @memberof TokenResponse
     */
    expiresIn: number;
    /**
     * 
     * @type {string}
     * @memberof TokenResponse
     */
    scope: string;
    /**
     * 
     * @type {string}
     * @memberof TokenResponse
     */
    identityAssertion?: string | null;
}

/**
 * Check if a given object implements the TokenResponse interface.
 */
export function instanceOfTokenResponse(value: object): value is TokenResponse {
    if ((!('accessToken' in value) && !('access_token' in value)) || (value['accessToken'] === undefined && value['access_token'] === undefined)) return false;
    if ((!('expiresIn' in value) && !('expires_in' in value)) || (value['expiresIn'] === undefined && value['expires_in'] === undefined)) return false;
    if (!('scope' in value) || value['scope'] === undefined) return false;
    return true;
}

export function TokenResponseFromJSON(json: any): TokenResponse {
    return TokenResponseFromJSONTyped(json, false);
}

export function TokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['access_token'],
        'tokenType': json['token_type'] == null ? undefined : json['token_type'],
        'expiresIn': json['expires_in'],
        'scope': json['scope'],
        'identityAssertion': json['identity_assertion'] == null ? undefined : json['identity_assertion'],
    };
}

export function TokenResponseToJSON(json: any): TokenResponse {
    return TokenResponseToJSONTyped(json, false);
}

export function TokenResponseToJSONTyped(value?: TokenResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_token': value['accessToken'],
        'token_type': value['tokenType'],
        'expires_in': value['expiresIn'],
        'scope': value['scope'],
        'identity_assertion': value['identityAssertion'],
    };
}

