/* tslint:disable */
/* eslint-disable */
/**
 * AgentDrive
 * AgentDrive is an agent-focused artifact store: upload by path, share by rendered URL, address by stable permalink. The REST surface is documented here; the rendered viewer + agent claim flow live under `agentdrive.run`.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VersionOut
 */
export interface VersionOut {
    /**
     * 
     * @type {string}
     * @memberof VersionOut
     */
    artId: string;
    /**
     * 
     * @type {number}
     * @memberof VersionOut
     */
    versionNumber: number;
    /**
     * 
     * @type {number}
     * @memberof VersionOut
     */
    sizeBytes: number;
    /**
     * 
     * @type {string}
     * @memberof VersionOut
     */
    hash: string;
    /**
     * 
     * @type {string}
     * @memberof VersionOut
     */
    contentType: string;
    /**
     * 
     * @type {string}
     * @memberof VersionOut
     */
    actorName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VersionOut
     */
    changeSummary?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof VersionOut
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the VersionOut interface.
 */
export function instanceOfVersionOut(value: object): value is VersionOut {
    if ((!('artId' in value) && !('art_id' in value)) || (value['artId'] === undefined && value['art_id'] === undefined)) return false;
    if ((!('versionNumber' in value) && !('version_number' in value)) || (value['versionNumber'] === undefined && value['version_number'] === undefined)) return false;
    if ((!('sizeBytes' in value) && !('size_bytes' in value)) || (value['sizeBytes'] === undefined && value['size_bytes'] === undefined)) return false;
    if (!('hash' in value) || value['hash'] === undefined) return false;
    if ((!('contentType' in value) && !('content_type' in value)) || (value['contentType'] === undefined && value['content_type'] === undefined)) return false;
    if ((!('createdAt' in value) && !('created_at' in value)) || (value['createdAt'] === undefined && value['created_at'] === undefined)) return false;
    return true;
}

export function VersionOutFromJSON(json: any): VersionOut {
    return VersionOutFromJSONTyped(json, false);
}

export function VersionOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionOut {
    if (json == null) {
        return json;
    }
    return {
        
        'artId': json['art_id'],
        'versionNumber': json['version_number'],
        'sizeBytes': json['size_bytes'],
        'hash': json['hash'],
        'contentType': json['content_type'],
        'actorName': json['actor_name'] == null ? undefined : json['actor_name'],
        'changeSummary': json['change_summary'] == null ? undefined : json['change_summary'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function VersionOutToJSON(json: any): VersionOut {
    return VersionOutToJSONTyped(json, false);
}

export function VersionOutToJSONTyped(value?: VersionOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'art_id': value['artId'],
        'version_number': value['versionNumber'],
        'size_bytes': value['sizeBytes'],
        'hash': value['hash'],
        'content_type': value['contentType'],
        'actor_name': value['actorName'],
        'change_summary': value['changeSummary'],
        'created_at': value['createdAt'].toISOString(),
    };
}

