/*
AgentDrive

Testing DrivesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package agentdrive

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/Mnexa-AI/agentdrive-sdk/agentdrive"
)

func Test_agentdrive_DrivesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DrivesAPIService CreateDriveRouteV0DrivesPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DrivesAPI.CreateDriveRouteV0DrivesPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DrivesAPIService ListDrivesRouteV0DrivesGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DrivesAPI.ListDrivesRouteV0DrivesGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DrivesAPIService RenameDriveRouteV0DrivesDriveIdPatch", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var driveId string

		resp, httpRes, err := apiClient.DrivesAPI.RenameDriveRouteV0DrivesDriveIdPatch(context.Background(), driveId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DrivesAPIService RotateDriveKeyRouteV0DrivesDriveIdKeysRotatePost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var driveId string

		resp, httpRes, err := apiClient.DrivesAPI.RotateDriveKeyRouteV0DrivesDriveIdKeysRotatePost(context.Background(), driveId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
