/*
AgentDrive

Testing McpOauthAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package agentdrive

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/Mnexa-AI/agentdrive-sdk/agentdrive"
)

func Test_agentdrive_McpOauthAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test McpOauthAPIService Oauth2RegisterOauth2RegisterPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.McpOauthAPI.Oauth2RegisterOauth2RegisterPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test McpOauthAPIService Oauth2RevokeOauth2RevokePost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.McpOauthAPI.Oauth2RevokeOauth2RevokePost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
