/*
AgentDrive

Testing MembersAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package agentdrive

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/Mnexa-AI/agentdrive-sdk/agentdrive"
)

func Test_agentdrive_MembersAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test MembersAPIService InviteMemberV0MembersInvitePost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.MembersAPI.InviteMemberV0MembersInvitePost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MembersAPIService ListInvitationsV0InvitationsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.MembersAPI.ListInvitationsV0InvitationsGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MembersAPIService ListMembersV0MembersGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.MembersAPI.ListMembersV0MembersGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MembersAPIService RemoveMemberV0MembersTargetUserIdDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var targetUserId string

		resp, httpRes, err := apiClient.MembersAPI.RemoveMemberV0MembersTargetUserIdDelete(context.Background(), targetUserId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MembersAPIService RevokeInvitationV0InvitationsInvitationIdDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var invitationId string

		resp, httpRes, err := apiClient.MembersAPI.RevokeInvitationV0InvitationsInvitationIdDelete(context.Background(), invitationId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MembersAPIService SetMemberRoleV0MembersTargetUserIdPatch", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var targetUserId string

		resp, httpRes, err := apiClient.MembersAPI.SetMemberRoleV0MembersTargetUserIdPatch(context.Background(), targetUserId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
