/*
AgentDrive

Testing FeedbackInternalAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package agentdrive

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/Mnexa-AI/agentdrive-sdk/agentdrive"
)

func Test_agentdrive_FeedbackInternalAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test FeedbackInternalAPIService AppendEventInternalFeedbackFbkIdEventsPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var fbkId string

		resp, httpRes, err := apiClient.FeedbackInternalAPI.AppendEventInternalFeedbackFbkIdEventsPost(context.Background(), fbkId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FeedbackInternalAPIService ContactInternalFeedbackFbkIdContactGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var fbkId string

		resp, httpRes, err := apiClient.FeedbackInternalAPI.ContactInternalFeedbackFbkIdContactGet(context.Background(), fbkId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FeedbackInternalAPIService GetAttachmentInternalFeedbackFbkIdAttachmentsFbaIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var fbkId string
		var fbaId string

		resp, httpRes, err := apiClient.FeedbackInternalAPI.GetAttachmentInternalFeedbackFbkIdAttachmentsFbaIdGet(context.Background(), fbkId, fbaId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FeedbackInternalAPIService GetTicketInternalFeedbackFbkIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var fbkId string

		resp, httpRes, err := apiClient.FeedbackInternalAPI.GetTicketInternalFeedbackFbkIdGet(context.Background(), fbkId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FeedbackInternalAPIService ListAttachmentsInternalFeedbackFbkIdAttachmentsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var fbkId string

		resp, httpRes, err := apiClient.FeedbackInternalAPI.ListAttachmentsInternalFeedbackFbkIdAttachmentsGet(context.Background(), fbkId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FeedbackInternalAPIService ListFeedbackInternalFeedbackGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.FeedbackInternalAPI.ListFeedbackInternalFeedbackGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FeedbackInternalAPIService NotifiedInternalFeedbackFbkIdNotifiedPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var fbkId string

		resp, httpRes, err := apiClient.FeedbackInternalAPI.NotifiedInternalFeedbackFbkIdNotifiedPost(context.Background(), fbkId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FeedbackInternalAPIService PendingNotificationsInternalFeedbackPendingNotificationsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.FeedbackInternalAPI.PendingNotificationsInternalFeedbackPendingNotificationsGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FeedbackInternalAPIService TransitionInternalFeedbackFbkIdTransitionPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var fbkId string

		resp, httpRes, err := apiClient.FeedbackInternalAPI.TransitionInternalFeedbackFbkIdTransitionPost(context.Background(), fbkId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
