/*
AgentDrive

Testing WorkspacesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package agentdrive

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/Mnexa-AI/agentdrive-sdk/agentdrive"
)

func Test_agentdrive_WorkspacesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test WorkspacesAPIService CreateWorkspaceRouteV0WorkspacesPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.WorkspacesAPI.CreateWorkspaceRouteV0WorkspacesPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorkspacesAPIService ListWorkspacesRouteV0WorkspacesGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.WorkspacesAPI.ListWorkspacesRouteV0WorkspacesGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WorkspacesAPIService RenameWorkspaceRouteV0WorkspacesOrgIdPatch", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var orgId string

		resp, httpRes, err := apiClient.WorkspacesAPI.RenameWorkspaceRouteV0WorkspacesOrgIdPatch(context.Background(), orgId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
